data = {
"resource": {
  "version":"466",
  
  "macros":[{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",0],8,16],".cart,b=[];a.forEach(function(a){b.push(a.id)});return b})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"category"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=[],b=",["escape",["macro",2],8,16],".items,c=4;for(i=0;i\u003Cmin(c,b.length);i++)a.push(b[i].id);return a})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"cart"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",4],8,16],",b=0;for(i=0;i\u003Ca.length;i++)b+=a[i].offers[0].price;return b})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",4],8,16],",b=[];a.forEach(function(a){b.push(a.id)});return b})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return String(",["escape",["macro",0],8,16],".id).replace(\/[^A-Za-z\\d]\/g,\"\")})();"]
    },{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventAction"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"GAevent\"==",["escape",["macro",8],8,16],"||\"test_GAevent\"==",["escape",["macro",8],8,16],"||\"GAEvent\"==",["escape",["macro",8],8,16],"?",["escape",["macro",9],8,16],":",["escape",["macro",8],8,16],"})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventCategory"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"GAevent\"==",["escape",["macro",8],8,16],"||\"test_GAevent\"==",["escape",["macro",8],8,16],"|\"GAEvent\"==",["escape",["macro",8],8,16],"?",["escape",["macro",11],8,16],":\"Enhanced Ecommerce\"})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventLabel"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"channel"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"GAevent\"==",["escape",["macro",8],8,16],"||\"listView\"==",["escape",["macro",8],8,16],"||\"test_GAevent\"==",["escape",["macro",8],8,16],"||\"GAEvent\"==",["escape",["macro",8],8,16],")return ",["escape",["macro",13],8,16],";if(\"Sale\"==",["escape",["macro",8],8,16],")return ",["escape",["macro",14],8,16],"})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventValue"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"GAevent\"==",["escape",["macro",8],8,16],"||\"test_GAevent\"==",["escape",["macro",8],8,16],"?",["escape",["macro",16],8,16],":",["escape",["macro",0],8,16],".revenue})();"]
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_source",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=\/(idealo)|(billiger)|(preisroboter)|(guenstiger)|(schottenland)|(testberichte)|(ladenzeile)|(moebel_de)|(kaufda)|(marktjagd)|(meinprospekt)|(mydealz)\/;if(",["escape",["macro",18],8,16],"\u0026\u0026",["escape",["macro",18],8,16],".match(a))return sessionStorage.setItem(\"cs_s\",\"0\"),\"start\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=document.createElement(\"ins\");a.className=\"AdSense\";a.style.display=\"block\";a.style.position=\"absolute\";a.style.top=\"-1px\";a.style.height=\"1px\";document.body.appendChild(a);var b=!a.clientHeight;document.body.removeChild(a);return b?\"yes\":\"no\"})();"]
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{return ",["escape",["macro",21],8,16],".match(\/^[\\w\\d-]+:\\\/\\\/([\\w\\d-]+\\.*)+\\\/?\/)[0]}catch(a){}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"undefined\"!=",["escape",["macro",23],8,16],")return null!=",["escape",["macro",24],8,16],".services.find(\"newsletter\")})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return null!=",["escape",["macro",24],8,16],".services.match(\"payback\")})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{return 0\u003Clen(",["escape",["macro",0],8,16],".payback.coupons)}catch(a){return!1}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",8],8,16],";return\"bannerView\"==a?!0:\"GAevent\"!=a||\"optimizely\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"ab test\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"Error Messages\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"feature\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"csSessionKey\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"view\"!=",["escape",["macro",9],8,16],"\u0026\u0026\"Payback\"!=",["escape",["macro",9],8,16],"?\"listView\"==a||\"listView_part2\"==a?!0:!1:!0})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"onlineshop\"==",["escape",["macro",14],8,16],"?\"nO_SCLu9vW4Q4ZSt0wM\":\"7J45CKn6t24Q4ZSt0wM\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"coupons\"in ",["escape",["macro",0],8,16],"){var a=0;for(i in ",["escape",["macro",0],8,16],".coupons)\"value\"in ",["escape",["macro",0],8,16],".coupons[i]\u0026\u0026(a+=",["escape",["macro",0],8,16],".coupons[i].value);return a}})();"]
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"category.pagination_start"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"search.pagination_start"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a;if(\"\/item\/search\/\"==",["escape",["macro",31],8,16],"\u0026\u0026",["escape",["macro",32],8,16],"|",["escape",["macro",33],8,16],")return a=parseInt((",["escape",["macro",32],8,16],"|",["escape",["macro",33],8,16],")\/40+1)})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"view.view_type"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"Item\"==",["escape",["macro",35],8,16],")return ",["escape",["macro",36],8,16],".category.join(\" \/ \");if(\"Category\"==",["escape",["macro",35],8,16],")return ",["escape",["macro",2],8,16],".path.join(\" \/ \")})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.market"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return-1!==",["escape",["macro",38],8,16],".indexOf(\"Liefergebiet\")?\"Delivery\":\"Click \\x26 Collect\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{return text_length=document.querySelector(\"._block.parent.prod-desc.col-sm-12.description\").textContent.length}catch(a){return 0}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(window.Storage){var a=sessionStorage.getItem(\"pb_sn\");return a}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var f=49;return function(c){var d=\"_\"+c.get(\"trackingId\")+\"_sendHitTask\",e=window[d]=window[d]||c.get(\"sendHitTask\");c.set(\"sendHitTask\",function(a){try{var c=a.get(\"hitPayload\"),b=a.get(\"hitPayload\"),d=\"\\x26cd\"+f;-1\u003Cb.indexOf(d+\"\\x3d\")?console.log(\"Google Analytics error: tried to send hit payload length in an already assigned Custom Dimension\"):(b+=d+\"\\x3d\",b+=b.length+b.length.toString().length,a.set(\"hitPayload\",b,!0));e(a)}catch(g){console.error(\"Error sending hit payload length to Google Analytics\"),\na.set(\"hitPayload\",c,!0),e(a)}})}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"undefined\"===",["escape",["macro",36],8,16],".seller_id?\"not set\":4397641==",["escape",["macro",36],8,16],".offers[0].seller_id?\"DV\":5415711==",["escape",["macro",36],8,16],".offers[0].seller_id?\"SP\":\"MP\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(window.Storage){var a=sessionStorage.getItem(\"cs_s\");return a}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=navigator.userAgent,b=\/\\[LMSAPP\\\/.*\\]\/;if(1==b.test(a))return a.split(\"[LMSAPP\/\")[1].replace(\"]\",\"\")})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=!1;\"undefined\"!=typeof ",["escape",["macro",23],8,16],"\u0026\u0026(a=void 0!=",["escape",["macro",23],8,16],");return a})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"undefined\"!=typeof document.cookie){var a=document.cookie;a=a.split(\"_ga\\x3d\");a=a[a.length-1];a=a.split(\";\");a=a[0];a=a.split(\".\");return a=a[2].concat(\".\",a[3])}return\"not set\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=window.RequestFileSystem||window.webkitRequestFileSystem;a\u0026\u0026a(0,100,function(a){browsermode=\"normal\"},function(a){browsermode=\"incognito\"});return browsermode})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return(new Date).getTime()+\".\"+Math.random().toString(36).substring(5)})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"search.search_term"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ecommerce.click.products"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(",["escape",["macro",35],8,16],"==\"Search\"){var ecomm=new Object;var listName=\"Search_\"+",["escape",["macro",50],8,16],";var searchProducts=new Array;var ecommProd=",["escape",["macro",51],8,16],";ecommProd.forEach(function(t){searchProducts.push({\"id\":t.id,\"name\":t.name,\"position\":t.position,\"category\":t.category,\"brand\":t.brand,\"list\":\"Search_t\\u00fcrkis\",\"price\":t.price,\"postition\":t.position})});ecomm={\"ecommerce\":{\"click\":{\"actionField\":{\"list\":\"Search_\"+",["escape",["macro",50],8,16],"},\"products\":searchProducts}}};return ecomm}})();"]
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"ref",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"Item\"==",["escape",["macro",35],8,16],"\u0026\u0026\"efood\"!=",["escape",["macro",14],8,16],")try{return-1!==",["escape",["macro",53],8,16],".indexOf(\"spa_\")?",["escape",["macro",53],8,16],":!1}catch(a){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=parseInt(window.innerWidth);if(480\u003Ea)return\"XXS\";if(480\u003C=a\u0026\u0026768\u003Ea)return\"XS\";if(468\u003C=a\u0026\u00261024\u003Ea)return\"SM\";if(1024\u003C=a\u0026\u00261280\u003Ea)return\"MD\";if(1280\u003C=a)return\"LG\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=window.performance.navigation.type;if(0==a)return\"navigate\";if(1==a)return\"reload\";if(2==a)return\"back or forward\";if(255==a)return\"reserved\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return window.location.protocol+\"\/\/\"+window.location.hostname+window.location.pathname+window.location.search})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"backend_ab_test.ga_exp_idvar"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return ",["escape",["macro",58],8,16],".join(\"!\")})();"]
    },{
      "function":"__jsm",
      "convert_null_to":["macro",57],
      "convert_undefined_to":["macro",57],
      "vtp_javascript":["template","(function(){if(window.Storage){var a=sessionStorage.getItem(\"ga_dl\");return a}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",14],8,16],",b=",["escape",["macro",31],8,16],",c=\/^\\\/pro\\\/\/,d=",["escape",["macro",35],8,16],",e=\/^brand$|^category$|^search$|^topic$\/;if(\"efood\"==a||\"onlineshop\"==a\u0026\u00261==e.test(d.toLowerCase())||1==c.test(b))return!0})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"addToCart\"==",["escape",["macro",8],8,16],"\u0026\u0026\"efood\"!==",["escape",["macro",14],8,16],")return document.referrer.split(\"\/\/www.real.de\/\")[1]})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.gmv"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",63],8,16],"-",["escape",["macro",0],8,16],".shipping_cost;return a})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return getCookie(\"AB-optimizely\")})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=JSON.parse(document.getElementById(\"06a5a104\").dataset.requestParams).title;if(\"to_be_replaced\"==a)return 1;if(\"Unsere Empfehlungen f\\u00fcr Sie\"==a)return 0})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return navigator.userAgent})();"]
    },{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.revenue"
    },{
      "function":"__u",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"view"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{vt=",["escape",["macro",71],8,16],".view_type;ev=",["escape",["macro",8],8,16],";if(vt==\"Category\"|vt==\"Search\"){maxItems=4;idList=",["escape",["macro",3],8,16],";r={\"ecomm_prodid\":",["escape",["macro",3],8,16],",\"ecomm_pagetype\":\"category\"}}else if(vt==\"Item\")r={\"ecomm_prodid\":",["escape",["macro",36],8,16],".id,\"ecomm_pagetype\":\"product\",\"ecomm_totalvalue\":",["escape",["macro",36],8,16],".offers.length\u003E0?",["escape",["macro",36],8,16],".offers[0].price:undefined};else if(ev==\"addToCart\"|vt==\"Cart\"|ev==\"RemoveFromCart\"|ev==\"Sale\"){if(ev==\"Sale\"){var pt=\n\"purchase\";var tv=",["escape",["macro",0],8,16],".revenue;var idList=",["escape",["macro",1],8,16],"}else{var pt=\"cart\";var tv=",["escape",["macro",5],8,16],";var idList=",["escape",["macro",6],8,16],"}r={\"ecomm_prodid\":idList,\"ecomm_pagetype\":pt,\"ecomm_totalvalue\":tv}}else r={\"ecomm_prodid\":\"\",\"ecomm_pagetype\":\"other\"};return r}catch(err){return{\"ecomm_prodid\":\"\",\"ecomm_pagetype\":\"other\"}}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"banners"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"promos"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"banner"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"promo"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"impressions"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ecommerce.click"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){function f(a){var b=[];try{a.forEach(function(a){b=b.concat(g(a))})}catch(m){}return b}function g(a){var b=[],d=0\u003Ca.offers.length?a.offers:[{availability:\"no offers\"}];d.forEach(function(c){var e={id:String(a.id),price:c.price?c.price.toString():void 0,dimension10:a.campaigns?String(a.campaigns):\"not set\",dimension73:a.favorite?String(a.favorite):\"false\"};c.revenue\u0026\u0026(e.metric1=c.revenue);c.amount\u0026\u0026(e.quantity=c.amount);if(\"efood\"!==",["escape",["macro",14],8,16],"){e.name=a.name;e.brand=a.brand;\ne.category=a.category.join(\"\/\");e.variant=a.variant;e.dimension8=void 0!==a.rating_average?parseFloat(a.rating_average).toFixed(1):void 0;e.dimension9=a.rating_num;e.dimension15=c.availability;e.dimension17=c.delivery_duration?c.delivery_duration:void 0;e.dimension18=void 0!==c.shipping_cost?c.shipping_cost.toString():void 0;e.dimension19=c.seller_id?c.seller_id:void 0;e.dimension20=c.condition?c.condition:void 0;e.dimension55=c.store_delivery?c.store_delivery:!1;var d=c.seller_id;d=\"undefined\"===\nd?\"not set\":4397641==d?\"DV\":5415711==d?\"SP\":\"MP\";e.dimension22=d;e.dimension31=a.ean;e.dimension43=c.price?c.price.toString():void 0;e.dimension46=c.uvp?c.uvp.toString():void 0;e.dimension57=a.licences?String(a.licences):\"not set\";e.metric9=c.payback}b.push(e)});return b}var b=",["escape",["macro",8],8,16],",d=",["escape",["macro",35],8,16],";if(\"bannerView\"==b||\"promoView\"==b){d=[];d=\"bannerView\"==b?",["escape",["macro",73],8,16],":",["escape",["macro",74],8,16],";var h=[];d.forEach(function(a){h.push({id:a.campaign_id?\"c\"+a.campaign_id+\n\":a\"+a.promotion_id:a.id,name:a.name,creative:a.promotion_name?a.promotion_name:void 0,position:a.carousel_position?a.page_position+\"_\"+a.carousel_position:a.page_position})});return{ecommerce:{promoView:{promotions:h}}}}if(\"bannerClick\"==b||\"promoClick\"==b)return b=\"bannerView\"==b?",["escape",["macro",75],8,16],"||",["escape",["macro",73],8,16],"[0]:",["escape",["macro",76],8,16],",b=",["escape",["macro",76],8,16],"||",["escape",["macro",75],8,16],"||",["escape",["macro",73],8,16],"[0],{ecommerce:{promoClick:{promotions:[{id:b.campaign_id?\"c\"+b.campaign_id+\":a\"+\nb.promotion_id:b.id,name:b.name,creative:b.promotion_name?b.promotion_name:void 0,position:b.carousel_position?b.page_position+\"_\"+b.carousel_position:b.page_position}]}}};if(\"listView\"==b||\"listView_part2\"==b){var l=[];b=",["escape",["macro",77],8,16],";b.forEach(function(a){l.push({id:a.id,name:a.name,position:a.position,category:a.category,brand:a.brand,list:a.list,price:a.price})});return{ecommerce:{impressions:b}}}if(\"listClick\"==b)return\"Search\"==",["escape",["macro",35],8,16],"\u0026\u0026\"onlineshop\"==",["escape",["macro",14],8,16],"?\n",["escape",["macro",52],8,16],":{ecommerce:{click:",["escape",["macro",78],8,16],"}};if(\"addToCart\"==b|\"removeFromCart\"==b)return p=",["escape",["macro",36],8,16],",p=\"[object Array]\"===Object.prototype.toString.call(p)?f(p):[g(p)[0]],\"addToCart\"==b?{ecommerce:{currencyCode:\"EUR\",add:{products:p}}}:{ecommerce:{remove:{products:p}}};if(\"Sale\"==b){d=",["escape",["macro",0],8,16],";var k=\"\";d.coupons\u0026\u0026d.coupons.forEach(function(a,b){k+=a.name+\" \"});b={id:String(d.id),revenue:\"efood\"==",["escape",["macro",14],8,16],"?\"0\":d.revenue.toString(),tax:d.tax.toString(),\nshipping:d.gmv.toString(),coupon:k};d=f(d.cart);return{ecommerce:{purchase:{actionField:b,products:d}}}}if(\"Item\"==d){if(\"pageView\"==b||void 0==b)return{ecommerce:{detail:{products:g(",["escape",["macro",36],8,16],")}}}}else if(\"Checkout\"==d\u0026\u0026\"pageView\"==b)return{ecommerce:{checkout:{actionField:{step:1},products:f(",["escape",["macro",4],8,16],")}}}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":["macro",31],
      "vtp_name":"view.virt_path"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){vt=",["escape",["macro",35],8,16],";vp=",["escape",["macro",80],8,16],";return\"Search\"==vt\u0026\u00260==vp.includes(\"\\x26q\\x3d\")?vp.includes(\"?\")?vp+\"\\x26q\\x3d\"+",["escape",["macro",50],8,16],":vp+\"?q\\x3d\"+",["escape",["macro",50],8,16],":",["escape",["macro",80],8,16],"})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"backend_ab_test.ga_exp_id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"backend_ab_test.ga_exp_var"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return-1!=",["escape",["macro",21],8,16],".search(\/(real\\.de)|(sofort\\.com)|(paypal\\.com)\/)?null:\"\/lebensmittelshop\/bestellung\/bestaetigung\/\"==",["escape",["macro",80],8,16],"||\"\/onlineshop\/checkout\/thankyou\/\"==",["escape",["macro",80],8,16],"?null:",["escape",["macro",21],8,16],"})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.payback.redeemed_points"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.payback.earned_points"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"search.results_number"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"category.results_number"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.age"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.gender"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.services"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"session.plz"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.selected_bkz"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"search.filter"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"session.terminal_id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"session.market_bkz"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.payment_method"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"cid",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.seller_id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"user.is_active_seller"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.delivery_type"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"next_store_distance"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"next_store_name"
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"real-cookie-msg"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.delivery_dow"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"efood_delivery_time"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"checkout.delivery_costs"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"c_cryptomail",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"tduid3"
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"category.filter"
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"_gaexp"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"recommenderLocation"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"modelName"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"recommenderVersion"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":1,
      "vtp_setDefaultValue":false,
      "vtp_name":"dataSource"
    },{
      "function":"__c",
      "vtp_value":"UA-27218006-5"
    },{
      "function":"__gas",
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_cookieDomain":"auto",
      "vtp_useEcommerceDataLayer":false,
      "vtp_ecommerceMacroData":["macro",79],
      "vtp_doubleClick":true,
      "vtp_setTrackerName":false,
      "vtp_fieldsToSet":["list",["map","fieldName","anonymizeIp","value","true"],["map","fieldName","page","value",["macro",81]],["map","fieldName","userId","value",["macro",23]],["map","fieldName","expId","value",["macro",82]],["map","fieldName","expVar","value",["macro",83]],["map","fieldName","referrer","value",["macro",84]],["map","fieldName","customTask","value",["macro",42]],["map","fieldName","exp","value",["macro",58]],["map","fieldName","location","value",["macro",60]]],
      "vtp_metric":["list",["map","index","3","metric",["macro",30]],["map","index","4","metric",["macro",85]],["map","index","5","metric",["macro",86]],["map","index","7","metric",["macro",87]],["map","index","8","metric",["macro",88]],["map","index","10","metric",["macro",40]]],
      "vtp_enableLinkId":false,
      "vtp_dimension":["list",["map","index","1","dimension",["macro",14]],["map","index","2","dimension",["macro",89]],["map","index","3","dimension",["macro",90]],["map","index","4","dimension",["macro",91]],["map","index","5","dimension",["macro",92]],["map","index","6","dimension",["macro",39]],["map","index","7","dimension",["macro",93]],["map","index","22","dimension",["macro",86]],["map","index","24","dimension",["macro",31]],["map","index","25","dimension",["macro",94]],["map","index","26","dimension",["macro",20]],["map","index","27","dimension",["macro",95]],["map","index","28","dimension",["macro",96]],["map","index","29","dimension",["macro",97]],["map","index","30","dimension",["macro",84]],["map","index","32","dimension",["macro",23]],["map","index","33","dimension",["macro",98]],["map","index","34","dimension",["macro",38]],["map","index","35","dimension",["macro",99]],["map","index","36","dimension",["macro",100]],["map","index","38","dimension",["macro",101]],["map","index","41","dimension",["macro",34]],["map","index","44","dimension",["macro",102]],["map","index","45","dimension",["macro",103]],["map","index","47","dimension",["macro",38]],["map","index","48","dimension",["macro",104]],["map","index","50","dimension",["macro",105]],["map","index","51","dimension",["macro",106]],["map","index","52","dimension",["macro",107]],["map","index","53","dimension",["macro",108]],["map","index","54","dimension",["macro",43]],["map","index","56","dimension",["macro",109]],["map","index","58","dimension",["macro",45]],["map","index","59","dimension",["macro",46]],["map","index","60","dimension",["macro",110]],["map","index","61","dimension",["macro",47]],["map","index","62","dimension",["macro",48]],["map","index","64","dimension",["macro",111]],["map","index","66","dimension",["macro",49]],["map","index","67","dimension",["macro",54]],["map","index","68","dimension",["macro",50]],["map","index","69","dimension",["macro",55]],["map","index","71","dimension",["macro",59]],["map","index","72","dimension",["macro",112]],["map","index","74","dimension",["macro",62]],["map","index","13","dimension",["macro",66]],["map","index","76","dimension",["macro",113]],["map","index","77","dimension",["macro",114]],["map","index","78","dimension",["macro",115]],["map","index","79","dimension",["macro",116]],["map","index","81","dimension",["macro",65]]],
      "vtp_enableEcommerce":true,
      "vtp_trackingId":["macro",117],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_ecommerceIsEnabled":true
    },{
      "function":"__gas",
      "vtp_useDebugVersion":false,
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_cookieDomain":"auto",
      "vtp_useEcommerceDataLayer":false,
      "vtp_ecommerceMacroData":["macro",79],
      "vtp_doubleClick":true,
      "vtp_setTrackerName":false,
      "vtp_fieldsToSet":["list",["map","fieldName","anonymizeIp","value","true"],["map","fieldName","page","value",["macro",81]],["map","fieldName","sessionControl","value",["macro",19]],["map","fieldName","userId","value",["macro",23]],["map","fieldName","expId","value",["macro",82]],["map","fieldName","expVar","value",["macro",83]],["map","fieldName","referrer","value",["macro",84]],["map","fieldName","customTask","value",["macro",42]],["map","fieldName","exp","value",["macro",59]],["map","fieldName","location","value",["macro",60]]],
      "vtp_metric":["list",["map","index","3","metric",["macro",30]],["map","index","4","metric",["macro",85]],["map","index","5","metric",["macro",86]],["map","index","7","metric",["macro",87]],["map","index","8","metric",["macro",88]],["map","index","10","metric",["macro",40]]],
      "vtp_enableLinkId":false,
      "vtp_dimension":["list",["map","index","1","dimension",["macro",14]],["map","index","2","dimension",["macro",89]],["map","index","3","dimension",["macro",90]],["map","index","4","dimension",["macro",91]],["map","index","5","dimension",["macro",92]],["map","index","6","dimension",["macro",39]],["map","index","7","dimension",["macro",93]],["map","index","22","dimension",["macro",86]],["map","index","24","dimension",["macro",31]],["map","index","25","dimension",["macro",94]],["map","index","26","dimension",["macro",20]],["map","index","27","dimension",["macro",95]],["map","index","28","dimension",["macro",96]],["map","index","29","dimension",["macro",97]],["map","index","30","dimension",["macro",84]],["map","index","32","dimension",["macro",23]],["map","index","33","dimension",["macro",98]],["map","index","34","dimension",["macro",38]],["map","index","35","dimension",["macro",99]],["map","index","36","dimension",["macro",100]],["map","index","38","dimension",["macro",101]],["map","index","41","dimension",["macro",34]],["map","index","44","dimension",["macro",102]],["map","index","45","dimension",["macro",103]],["map","index","47","dimension",["macro",38]],["map","index","48","dimension",["macro",104]],["map","index","50","dimension",["macro",105]],["map","index","51","dimension",["macro",106]],["map","index","52","dimension",["macro",107]],["map","index","53","dimension",["macro",108]],["map","index","54","dimension",["macro",43]],["map","index","56","dimension",["macro",109]],["map","index","58","dimension",["macro",45]],["map","index","59","dimension",["macro",46]],["map","index","60","dimension",["macro",110]],["map","index","61","dimension",["macro",47]],["map","index","62","dimension",["macro",48]],["map","index","64","dimension",["macro",111]],["map","index","66","dimension",["macro",49]],["map","index","67","dimension",["macro",54]],["map","index","68","dimension",["macro",50]],["map","index","69","dimension",["macro",55]],["map","index","70","dimension",["macro",56]],["map","index","71","dimension",["macro",59]],["map","index","72","dimension",["macro",112]],["map","index","81","dimension",["macro",65]],["map","index","82","dimension",["macro",67]]],
      "vtp_enableEcommerce":true,
      "vtp_trackingId":["macro",117],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_ecommerceIsEnabled":true
    },{
      "function":"__r"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"Sale\"==",["escape",["macro",8],8,16],")return ",["escape",["macro",79],8,16],".ecommerce.purchase.products})();"]
    },{
      "function":"__v",
      "vtp_name":"gtm.errorMessage",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.errorLineNumber",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.errorUrl",
      "vtp_dataLayerVersion":1
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){if(\"Item\"==",["escape",["macro",35],8,16],")return ",["escape",["macro",36],8,16],".brand;if(\"Brand\"==",["escape",["macro",35],8,16],"){var a=",["escape",["macro",80],8,16],".match(\/[^\\\/]+$\/);return null!=a?a[0]:null}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product.id"
    },{
      "function":"__v",
      "vtp_name":"gtm.triggers",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":""
    },{
      "function":"__v",
      "vtp_name":"gtm.videoTitle",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.videoStatus",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.videoPercent",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementClasses",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.scrollThreshold",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.element",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"gtm.historyChangeSource"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product.brand"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product.rating_num"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product.rating_average"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"product.category"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"tduid",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"search.items"
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"coopPartner"
    },{
      "function":"__v",
      "vtp_name":"gtm.elementId",
      "vtp_dataLayerVersion":1
    },{
      "function":"__c",
      "vtp_value":"real.de"
    },{
      "function":"__c",
      "vtp_value":"UA-27218006-4"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"category.title"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"view.ga_exp_id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"view.ga_exp_var"
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_fieldsToSet":["list",["map","fieldName","anonymizeIp","value","true"],["map","fieldName","page","value",["macro",81]],["map","fieldName","userId","value",["macro",23]],["map","fieldName","expId","value",["macro",82]],["map","fieldName","expVar","value",["macro",83]],["map","fieldName","allowAnchor","value","true"],["map","fieldName","cookieDomain","value","auto"],["map","fieldName","sessionControl","value",["macro",19]]],
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_autoLinkDomains":"real-foto.de,real-blumen.de,real.de",
      "vtp_enableLinkId":false,
      "vtp_dimension":["list",["map","index","1","dimension",["macro",14]]],
      "vtp_enableEcommerce":false,
      "vtp_trackingId":["macro",144],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__c",
      "vtp_value":"real-foto.de, real-blumen.de, real.de"
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_name":"gtm.elementTarget",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementUrl",
      "vtp_dataLayerVersion":1
    },{
      "function":"__aev",
      "vtp_varType":"TEXT"
    },{
      "function":"__r"
    },{
      "function":"__v",
      "vtp_name":"gtm.videoUrl",
      "vtp_dataLayerVersion":1
    }],
  "tags":[{
      "function":"__awct",
      "once_per_event":true,
      "vtp_conversionValue":["macro",69],
      "vtp_orderId":["macro",7],
      "vtp_conversionId":"980109921",
      "vtp_currencyCode":"EUR",
      "vtp_conversionLabel":["macro",29],
      "vtp_url":["macro",70],
      "vtp_enableProductReportingCheckbox":true,
      "vtp_enableEnhancedConversionsCheckbox":false,
      "tag_id":1
    },{
      "function":"__sp",
      "once_per_event":true,
      "vtp_enableDynamicRemarketing":false,
      "vtp_dataLayerVariable":["macro",72],
      "vtp_conversionId":"980109921",
      "vtp_customParamsFormat":"DATA_LAYER",
      "vtp_conversionLabel":"nO_SCLu9vW4Q4ZSt0wM",
      "vtp_enableOgtRmktParams":true,
      "vtp_url":["macro",70],
      "tag_id":2
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":["macro",28],
      "vtp_overrideGaSettings":false,
      "vtp_eventValue":["macro",17],
      "vtp_eventCategory":["macro",12],
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":["macro",10],
      "vtp_eventLabel":["macro",15],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":23
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",119],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":24
    },{
      "function":"__flc",
      "vtp_customVariable":["list",["map","key","u1","value",["macro",25]],["map","key","u2","value",["macro",26]],["map","key","u4","value",["macro",89]],["map","key","u5","value",["macro",90]]],
      "vtp_enableConversionLinker":true,
      "vtp_groupTag":"real-0",
      "vtp_useImageTag":false,
      "vtp_activityTag":"dcm_r0",
      "vtp_ordinalType":"STANDARD",
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_advertiserId":"6487026",
      "vtp_ordinalStandard":["macro",120],
      "vtp_url":["macro",70],
      "vtp_enableGoogleAttributionOptions":false,
      "vtp_showConversionLinkingControls":true,
      "tag_id":35
    },{
      "function":"__fls",
      "vtp_customVariable":["list",["map","key","u1","value",["macro",25]],["map","key","u2","value",["macro",26]],["map","key","u3","value",["macro",63]],["map","key","u4","value",["macro",89]],["map","key","u5","value",["macro",90]],["map","key","u11","value",["macro",27]],["map","key","u12","value",["macro",97]],["map","key","u14","value",["macro",14]]],
      "vtp_countingMethod":"TRANSACTIONS",
      "vtp_orderId":["macro",7],
      "vtp_enableProductReporting":true,
      "vtp_useImageTag":false,
      "vtp_productData":["macro",121],
      "vtp_advertiserId":"6487026",
      "vtp_revenue":["macro",69],
      "vtp_enableConversionLinker":true,
      "vtp_groupTag":"real-1",
      "vtp_activityTag":"dcm_s0",
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_dataSource":"JSON",
      "vtp_countingMethodIsTransactions":true,
      "vtp_url":["macro",70],
      "vtp_enableGoogleAttributionOptions":false,
      "vtp_showConversionLinkingControls":true,
      "tag_id":36
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"JavaScript Error",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":["macro",122],
      "vtp_eventLabel":["template",["macro",123],":",["macro",124]],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":52
    },{
      "function":"__flc",
      "vtp_customVariable":["list",["map","key","u1","value",["macro",25]],["map","key","u2","value",["macro",26]],["map","key","u4","value",["macro",89]],["map","key","u5","value",["macro",90]],["map","key","u13","value",["macro",22]],["map","key","u3","value",["macro",5]],["map","key","u6","value",["macro",92]],["map","key","u7","value",["macro",50]],["map","key","u8","value",["macro",37]],["map","key","u9","value",["macro",125]],["map","key","u10","value",["macro",93]],["map","key","u11","value",["macro",27]],["map","key","u12","value",["macro",97]],["map","key","u14","value",["macro",14]],["map","key","u15","value",["macro",80]],["map","key","u16","value",["macro",35]],["map","key","u17","value",["macro",126]]],
      "vtp_enableConversionLinker":true,
      "vtp_groupTag":"real-0",
      "vtp_useImageTag":false,
      "vtp_activityTag":"dcm_p00",
      "vtp_ordinalType":"STANDARD",
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_advertiserId":"6487026",
      "vtp_ordinalStandard":["macro",120],
      "vtp_url":["macro",70],
      "vtp_enableGoogleAttributionOptions":false,
      "vtp_showConversionLinkingControls":true,
      "tag_id":63
    },{
      "function":"__fls",
      "vtp_customVariable":["list",["map","key","u1","value",["macro",25]],["map","key","u2","value",["macro",26]],["map","key","u3","value",["macro",63]],["map","key","u4","value",["macro",89]],["map","key","u5","value",["macro",90]],["map","key","u11","value",["macro",27]],["map","key","u12","value",["macro",97]],["map","key","u14","value",["macro",14]]],
      "vtp_countingMethod":"TRANSACTIONS",
      "vtp_orderId":["macro",7],
      "vtp_enableProductReporting":true,
      "vtp_useImageTag":false,
      "vtp_productData":["macro",121],
      "vtp_advertiserId":"6487026",
      "vtp_revenue":["macro",69],
      "vtp_enableConversionLinker":true,
      "vtp_groupTag":"real-1",
      "vtp_activityTag":"sales0",
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_dataSource":"JSON",
      "vtp_countingMethodIsTransactions":true,
      "vtp_url":["macro",70],
      "vtp_enableGoogleAttributionOptions":false,
      "vtp_showConversionLinkingControls":true,
      "tag_id":68
    },{
      "function":"__img",
      "once_per_event":true,
      "vtp_useCacheBuster":true,
      "vtp_url":"https:\/\/backend.real-newsletter.de\/action\/conv\/",
      "vtp_cacheBusterQueryParam":"gtmcb",
      "vtp_randomNumber":["macro",120],
      "tag_id":73
    },{
      "function":"__baut",
      "once_per_event":true,
      "vtp_goalValue":["macro",69],
      "vtp_eventValue":["macro",69],
      "vtp_eventCategory":"ecommerce",
      "vtp_tagId":"5999241",
      "vtp_uetqName":"uetq",
      "vtp_eventType":"CUSTOM",
      "vtp_eventAction":"sale",
      "vtp_eventLabel":["macro",14],
      "tag_id":74
    },{
      "function":"__baut",
      "once_per_event":true,
      "vtp_tagId":"5999241",
      "vtp_uetqName":"uetq",
      "vtp_eventType":"PAGE_LOAD",
      "tag_id":75
    },{
      "function":"__gclidw",
      "once_per_event":true,
      "vtp_enableCrossDomain":false,
      "vtp_enableCookieOverrides":false,
      "vtp_enableCrossDomainFeature":true,
      "vtp_enableCookieUpdateFeature":false,
      "tag_id":85
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"Youtube Video click",
      "vtp_eventLabel":["template",["macro",128],"_",["macro",129]],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":108
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"Youtube Video Progress",
      "vtp_eventLabel":["template",["macro",128],"_",["macro",130],"%"],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":109
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"header login clicked",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":124
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventValue":["macro",40],
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"product description viewed",
      "vtp_eventLabel":["macro",31],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":133
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventValue":["macro",40],
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"more information on product description clicked",
      "vtp_eventLabel":["macro",31],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":134
    },{
      "function":"__flc",
      "vtp_enableConversionLinker":true,
      "vtp_groupTag":"real-0",
      "vtp_useImageTag":false,
      "vtp_activityTag":"realp0",
      "vtp_ordinalType":"UNIQUE",
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_advertiserId":"6487026",
      "vtp_ordinalUnique":"1",
      "vtp_number":["macro",120],
      "vtp_url":["macro",70],
      "vtp_enableGoogleAttributionOptions":false,
      "vtp_showConversionLinkingControls":true,
      "tag_id":135
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"engagement",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"scrolling",
      "vtp_eventLabel":["template",["macro",132],"%"],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":148
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",119],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":154
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"abtest",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"activate",
      "vtp_eventLabel":["macro",59],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":158
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"feature",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"ratgeber viewed",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":170
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"feature",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",118],
      "vtp_eventAction":"ad viewed",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":179
    },{
      "function":"__cl",
      "tag_id":183
    },{
      "function":"__cl",
      "tag_id":184
    },{
      "function":"__jel",
      "tag_id":185
    },{
      "function":"__hl",
      "tag_id":186
    },{
      "function":"__ytl",
      "vtp_captureComplete":false,
      "vtp_captureStart":true,
      "vtp_fixMissingApi":true,
      "vtp_triggerStartOption":"DOM_READY",
      "vtp_capturePause":true,
      "vtp_captureProgress":false,
      "vtp_uniqueTriggerId":"6178770_643",
      "vtp_enableTriggerStartOption":true,
      "tag_id":187
    },{
      "function":"__ytl",
      "vtp_progressThresholdsPercent":"25, 50, 75, 100",
      "vtp_captureComplete":false,
      "vtp_captureStart":false,
      "vtp_fixMissingApi":true,
      "vtp_triggerStartOption":"DOM_READY",
      "vtp_radioButtonGroup1":"PERCENTAGE",
      "vtp_capturePause":false,
      "vtp_captureProgress":true,
      "vtp_uniqueTriggerId":"6178770_646",
      "vtp_enableTriggerStartOption":true,
      "tag_id":188
    },{
      "function":"__lcl",
      "vtp_waitForTags":false,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"6178770_705",
      "tag_id":189
    },{
      "function":"__evl",
      "vtp_elementId":"produktinformationen",
      "vtp_useOnScreenDuration":true,
      "vtp_useDomChangeListener":true,
      "vtp_firingFrequency":"ONCE_PER_ELEMENT",
      "vtp_selectorType":"ID",
      "vtp_onScreenRatio":"20",
      "vtp_onScreenDuration":"1000",
      "vtp_uniqueTriggerId":"6178770_730",
      "tag_id":190
    },{
      "function":"__cl",
      "tag_id":191
    },{
      "function":"__sdl",
      "vtp_verticalThresholdUnits":"PERCENT",
      "vtp_verticalThresholdsPercent":"25,50,75,100",
      "vtp_verticalThresholdOn":true,
      "vtp_triggerStartOption":"WINDOW_LOAD",
      "vtp_horizontalThresholdOn":false,
      "vtp_uniqueTriggerId":"6178770_780",
      "vtp_enableTriggerStartOption":true,
      "tag_id":192
    },{
      "function":"__cl",
      "tag_id":193
    },{
      "function":"__cl",
      "tag_id":194
    },{
      "function":"__lcl",
      "vtp_waitForTags":false,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"6178770_843",
      "tag_id":195
    },{
      "function":"__evl",
      "vtp_elementId":"ratgeber",
      "vtp_useOnScreenDuration":false,
      "vtp_useDomChangeListener":true,
      "vtp_firingFrequency":"ONCE_PER_ELEMENT",
      "vtp_selectorType":"ID",
      "vtp_onScreenRatio":"1",
      "vtp_uniqueTriggerId":"6178770_879",
      "tag_id":196
    },{
      "function":"__evl",
      "vtp_elementId":"wide_additional_products_unit",
      "vtp_useOnScreenDuration":false,
      "vtp_useDomChangeListener":true,
      "vtp_firingFrequency":"ONCE",
      "vtp_selectorType":"ID",
      "vtp_onScreenRatio":"1",
      "vtp_uniqueTriggerId":"6178770_895",
      "tag_id":197
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\n\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_facebook\"\u003Evar ev=",["escape",["macro",8],8,16],";\nfunction params(){var a={shop:",["escape",["macro",14],8,16],"};if(\"Item\"==",["escape",["macro",35],8,16],"){try{a.brand=",["escape",["macro",36],8,16],".brand}catch(c){a.brand=\"noname\"}try{a.category=",["escape",["macro",36],8,16],".category.join(\" \/ \")+\"$\"}catch(c){}}else if(\"Category\"==",["escape",["macro",35],8,16],")try{a.category=",["escape",["macro",2],8,16],".path.join(\" \/ \")+\"$\"}catch(c){}else if(\"Brand\"==",["escape",["macro",35],8,16],")try{a.brand=",["escape",["macro",80],8,16],".replace(\"\/onlineshop\/marken\/\",\"\")}catch(c){a.brand=\"noname\"}a.user_is_newsletter=",["escape",["macro",25],8,16],";\na.user_is_seller=",["escape",["macro",100],8,16],";a.user_is_payback=",["escape",["macro",26],8,16],";a.market_name=",["escape",["macro",38],8,16],";return a}function getContents(a){var c=[],d=[];\"sale\"==a?d=",["escape",["macro",0],8,16],".cart:(a=",["escape",["macro",36],8,16],",d.push(a));for(i=0;i\u003Cd.length;i++)c.push({id:d[i].id,item_price:d[i].offers[0].price,quantity:d[i].offers[0].amount});return c}\nif(\"pageView\"==ev){\"undefined\"===typeof fbq\u0026\u0026(!function(a,c,d,g,b,e,f){a.fbq||(b=a.fbq=function(){b.callMethod?b.callMethod.apply(b,arguments):b.queue.push(arguments)},a._fbq||(a._fbq=b),b.push=b,b.loaded=!0,b.version=\"2.0\",b.queue=[],e=c.createElement(d),e.async=!0,e.src=g,f=c.getElementsByTagName(d)[0],f.parentNode.insertBefore(e,f))}(window,document,\"script\",\"https:\/\/connect.facebook.net\/en_US\/fbevents.js\"),fbq(\"init\",\"567296886762376\"));fbq(\"track\",\"PageView\",params());var vt=",["escape",["macro",71],8,16],".view_type;\nif(\"Item\"==vt){var par=params();par.content_category=",["escape",["macro",14],8,16],";par.content_type=\"product\";par.currency=\"EUR\";try{par.contents=getContents()}catch(a){}try{par.content_ids=[",["escape",["macro",36],8,16],".id]}catch(a){}try{par.value=",["escape",["macro",36],8,16],".offers[0].price}catch(a){par.value=0}fbq(\"track\",\"ViewContent\",par)}else\"Checkout\"==vt\u0026\u0026fbq(\"track\",\"InitiateCheckout\")}else if(\"addToCart\"==ev){par=params();par.content_type=\"product\";par.currency=\"EUR\";try{par.contents=getContents()}catch(a){}try{par.content_ids=\n[",["escape",["macro",36],8,16],".id]}catch(a){}try{par.value=",["escape",["macro",36],8,16],".offers[0].price}catch(a){par.value=0}fbq(\"track\",\"AddToCart\",par)}else if(\"Sale\"==ev){par=params();par.content_type=\"product\";par.currency=\"EUR\";par.payment_method=",["escape",["macro",97],8,16],";try{par.contents=getContents(\"sale\")}catch(a){}par.content_ids=",["escape",["macro",1],8,16],";par.value=Math.max(0,",["escape",["macro",0],8,16],".revenue)||0;fbq(\"track\",\"Purchase\",par)}else\"GAevent\"!=ev||\"engagement\"!=",["escape",["macro",11],8,16],"\u0026\u0026\"disengagement\"!=\n",["escape",["macro",11],8,16],"||\"user login\"==",["escape",["macro",9],8,16],"||\"user logout\"==",["escape",["macro",11],8,16],"||(par={shop:",["escape",["macro",14],8,16],",eventCategory:",["escape",["macro",11],8,16],",eventAction:",["escape",["macro",9],8,16],",eventLabel:",["escape",["macro",13],8,16],"},fbq(\"trackCustom\",\"event\",par));\u003C\/script\u003E\n  \n  \n  \t\t"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":4
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_cs_sale\"\u003Ewindow._uxa=window._uxa||[];var ckt=",["escape",["macro",0],8,16],";window._uxa.push([\"ecommerce:addTransaction\",{id:String(ckt.id),revenue:ckt.gmv.toString(),tax:ckt.tax.toString()}]);var pds=[];ckt.cart.forEach(function(a){a.offers.forEach(function(b){window._uxa.push([\"ecommerce:addItem\",{id:String(ckt.id),name:a.name,sku:String(a.id),category:a.category[a.category.length-1],price:b.price.toString(),quantity:b.amount}])})});window._uxa.push([\"ecommerce:send\"]);\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":17
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_cs_registeronloginform\"\u003Ewindow._uxa=window._uxa||[];window._uxa.push([\"trackPageview\",window.location.pathname+\"?cs-popin-register\"]);\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":20
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_cs_cancelloginform\"\u003Ewindow._uxa=window._uxa||[];window._uxa.push([\"trackPageview\",window.location.pathname+\"?cs-popin-login\"]);\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":21
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_instorefunction\"\u003Evar getUrlVars=function(d){var b=[];var a=window.location.href.slice(window.location.href.indexOf(\"?\")+1);0\u003C=a.lastIndexOf(window.location.hash)\u0026\u0026(a=a.substring(0,a.lastIndexOf(window.location.hash)));for(var c=a.split(\"\\x26\"),e=0;e\u003Cc.length;e++)a=c[e].split(\"\\x3d\"),b.push(a[0]),b[a[0]]=a[1];return d?b[d]:b};function setCookie(d,b,a){var c=new Date;c.setTime(c.getTime()+864E5*a);a=\"expires\\x3d\"+c.toUTCString();document.cookie=d+\"\\x3d\"+b+\";\"+a+\";path\\x3d\/\"}\nfunction getCookie(d){d+=\"\\x3d\";var b=decodeURIComponent(document.cookie);b=b.split(\";\");for(var a=0;a\u003Cb.length;a++){for(var c=b[a];\" \"==c.charAt(0);)c=c.substring(1);if(0==c.indexOf(d))return c.substring(d.length,c.length)}return!1}\n(function(){var d=4E3,b=function(){window.SSO\u0026\u0026window.SSO.SSO\u0026\u0026window.SSO.SSO.isInitialized()?(window.setTimeout(b,d),window.SSO.SSO.logout()):getCookie(\"real-force-logout\")\u0026\u0026setCookie(\"real-force-logout\",0,0)};\"Sale\"==",["escape",["macro",8],8,16],"?getCookie(\"real-terminal-id\")\u0026\u0026setCookie(\"real-force-logout\",\"1\",7):(getUrlVars(\"real-market-bkz\")\u0026\u0026getUrlVars(\"real-terminal-id\")\u0026\u0026(setCookie(\"real-market-bkz\",getUrlVars(\"real-market-bkz\"),7),setCookie(\"real-terminal-id\",getUrlVars(\"real-terminal-id\"),7)),getCookie(\"real-force-logout\")\u0026\u0026\nwindow.setTimeout(b,d))})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":22
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_cs_popups\"\u003Ewindow._uxa=window._uxa||[];\"popups\"==",["escape",["macro",11],8,16],"\u0026\u0026\"open\"==",["escape",["macro",9],8,16],"\u0026\u0026\"marktauswahl\"==",["escape",["macro",13],8,16],"?window._uxa.push([\"trackPageview\",window.location.pathname+\"?cs-popin-changemarket\"]):\"popups\"==",["escape",["macro",11],8,16],"\u0026\u0026\"close\"==",["escape",["macro",9],8,16],"\u0026\u0026\"marktauswahl\"==",["escape",["macro",13],8,16],"\u0026\u0026window._uxa.push([\"trackPageview\",window.location.pathname]);\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":25
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_NLevents\"\u003E(function(){if(\"\/newsletter\/abmeldung\/\"==",["escape",["macro",80],8,16],")var a={event:\"GAevent\",eventCategory:\"disengagement\",eventAction:\"newsletter signoff\"};else\"\/newsletter\/bestaetigung\/\"==",["escape",["macro",80],8,16],"\u0026\u0026(a={event:\"GAevent\",eventCategory:\"engagement\",eventAction:\"newsletter confirmation\"});dataLayer.push(a)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":53
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/javascript\" id=\"gtmctagid_lego_DCMconversion\"\u003Efunction fl_product(b,c,d,e,f,g){var a=Math.random()+\"\";a*=1E13;document.write('\\x3ciframe src\\x3d\"https:\/\/8342968.fls.doubleclick.net\/activityi;src\\x3d8342968;type\\x3dflash;cat\\x3dreal;u1\\x3d",["escape",["macro",7],7],";u6\\x3d'+b+\";u7\\x3d\"+c+\";u8\\x3d\"+d+\";u9\\x3d\"+e+\";u10\\x3d\"+f+\";u11\\x3d\"+g+\";dc_lat\\x3d;dc_rdid\\x3d;tag_for_child_directed_treatment\\x3d;ord\\x3d\"+a+'?\" height\\x3d\"0\" width\\x3d\"0\" style\\x3d\"display: none; visibility: hidden\"\\x3e\\x3c\/iframe\\x3e')}var m=0,n=0;\nfor(i=0;i\u003C",["escape",["macro",0],8,16],".cart.length;i++){var p=",["escape",["macro",0],8,16],".cart[i];for(j=0;j\u003Cp.offers.length;j++){var o=p.offers[j];m+=o.amount;if(\"brand\"in p\u0026\u0026null!=p.brand.match(\/\\blego\\b\/i)\u0026\u0026(n+=o.amount,\"seller_id\"in o\u0026\u0026null!=o.seller_id.match(\/^4397641$|^5415711$\/)))for(k=0;k\u003Co.amount;k++)fl_product(o.seller_id,o.price,p.id,p.name,p.ean,void 0)}}\ndocument.write('\\x3ciframe src\\x3d\"https:\/\/8342968.fls.doubleclick.net\/activityi;src\\x3d8342968;type\\x3dflash;cat\\x3dreal;qty\\x3d1;cost\\x3d",["escape",["macro",63],7],";u1\\x3d",["escape",["macro",7],7],";u2\\x3d'+m+\";u3\\x3d\"+n+';dc_lat\\x3d;dc_rdid\\x3d;tag_for_child_directed_treatment\\x3d;ord\\x3d",["escape",["macro",7],7],"?\" height\\x3d\"0\" width\\x3d\"0\" style\\x3d\"display: none; visibility: hidden\"\\x3e\\x3c\/iframe\\x3e');\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":true,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "vtp_usePostscribe":true,
      "tag_id":56
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_CS_pageview\"\u003E(function(){window._uxa=window._uxa||[];window._uxa.push([\"setPath\",window.location.pathname+window.location.hash.replace(\"#\",\"?__\")]);try{\"undefined\"!==typeof dataLayer\u0026\u0026(void 0!==",["escape",["macro",14],8,16],"?window._uxa.push([\"setCustomVariable\",1,\"channel\",",["escape",["macro",14],8,16],",3]):void 0,void 0!==",["escape",["macro",126],8,16],"?window._uxa.push([\"setCustomVariable\",2,\"product_id\",",["escape",["macro",126],8,16],",3]):void 0,void 0!==",["escape",["macro",135],8,16],"?window._uxa.push([\"setCustomVariable\",3,\"product_brand\",",["escape",["macro",135],8,16],",\n3]):void 0,void 0!==",["escape",["macro",90],8,16],"?window._uxa.push([\"setCustomVariable\",4,\"gender\",",["escape",["macro",90],8,16],",3]):void 0,void 0!==",["escape",["macro",35],8,16],"?window._uxa.push([\"setCustomVariable\",5,\"view_type\",",["escape",["macro",35],8,16],",3]):void 0,void 0!==",["escape",["macro",80],8,16],"?window._uxa.push([\"setCustomVariable\",6,\"virt_path\",",["escape",["macro",80],8,16],",3]):void 0,void 0!==",["escape",["macro",136],8,16],"?window._uxa.push([\"setCustomVariable\",7,\"rating_num\",",["escape",["macro",136],8,16],",3]):void 0,void 0!==",["escape",["macro",137],8,16],"?\nwindow._uxa.push([\"setCustomVariable\",8,\"rating_average\",",["escape",["macro",137],8,16],",3]):void 0,void 0!==",["escape",["macro",138],8,16],"?window._uxa.push([\"setCustomVariable\",9,\"product_category\",String(",["escape",["macro",138],8,16],"),3]):void 0,void 0!==",["escape",["macro",50],8,16],"?window._uxa.push([\"setCustomVariable\",10,\"search_term\",",["escape",["macro",50],8,16],",3]):void 0,void 0!==",["escape",["macro",91],8,16],"?window._uxa.push([\"setCustomVariable\",11,\"user_services\",",["escape",["macro",91],8,16],",3]):void 0,void 0!==",["escape",["macro",38],8,16],"?window._uxa.push([\"setCustomVariable\",\n12,\"market_name\",",["escape",["macro",38],8,16],",3]):void 0,void 0!==",["escape",["macro",58],8,16],"?window._uxa.push([\"trackDynamicVariable\",{key:\"backend_abtest\",value:",["escape",["macro",58],8,16],".toString()}]):void 0,void 0!==",["escape",["macro",112],8,16],"?window._uxa.push([\"trackDynamicVariable\",{key:\"client_abtest\",value:",["escape",["macro",112],8,16],"}]):void 0,void 0!==",["escape",["macro",87],8,16],"?window._uxa.push([\"setCustomVariable\",15,\"search results\",String(",["escape",["macro",87],8,16],"),3]):void 0,void 0!==",["escape",["macro",46],8,16],"?window._uxa.push([\"setCustomVariable\",\n16,\"logged_in_status\",String(",["escape",["macro",46],8,16],"),3]):void 0,void 0!==",["escape",["macro",47],8,16],"?window._uxa.push([\"setCustomVariable\",17,\"GA_client_ID\",String(",["escape",["macro",47],8,16],"),3]):void 0)}catch(b){}if(\"undefined\"===typeof CS_CONF){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"\/\/t.contentsquare.net\/uxa\/8fb48415ac213.js\";document.getElementsByTagName(\"head\")[0].appendChild(a)}else window._uxa.push([\"trackPageview\",window.location.pathname+window.location.hash.replace(\"#\",\n\"?__\")])})();\"1\"!=",["escape",["macro",44],8,16],"\u0026\u0026(window._uxa.push([\"getSessionKey\",{callback:function(a){dataLayer.push({event:\"GAevent\",eventCategory:\"csSessionKey\",eventAction:a,eventLabel:void 0,eventValue:void 0})}}]),sessionStorage.setItem(\"cs_s\",\"1\"));\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":59
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_cleanup\"\u003Evar q_gtm;q_gtm=document.querySelectorAll(\"[id^\\x3dgtmctagid_]\");for(var i=q_gtm.length;0\u003Ci;i--)void 0!=q_gtm[i]\u0026\u0026q_gtm[i].remove();\u003C\/script\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":72
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_payback_campaign\"\u003Efunction pb_ck(c,d,a){a*=1E3;var b=new Date,e=b.getTime();b.setTime(e+a);a=b.toUTCString();document.cookie=c+\"\\x3d\"+d+\"; expires\\x3d\"+a+\"; path\\x3d\/; domain\\x3d.\"+location.hostname.replace(\/^www\\.\/i,\"\")}var re=\/(?=.*?\\butm_source=payback\\b)(?=.*?\\butm_medium=paid\\b)(?=.*?\\btduid=\\b)(?=(.*?\\butm_campaign=payback%20page\\b))^.*$\/;\nwindow.Storage\u0026\u0026(1==re.test(",["escape",["macro",110],8,16],")\u0026\u0026\"0\"!=",["escape",["macro",109],8,16],"?pb_ck(\"tduid3\",",["escape",["macro",139],8,16],",2592E3):",["escape",["macro",110],8,16],".match(\/(utm_.*=)|(gclid=)\/)\u0026\u00260==re.test(",["escape",["macro",110],8,16],")?pb_ck(\"tduid3\",0,2592E3):(0!=re.test(",["escape",["macro",110],8,16],")||\"0\"!=",["escape",["macro",109],8,16],"\u0026\u0026void 0!=",["escape",["macro",109],8,16],"||\"1\"==sessionStorage.getItem(\"pb_sn\")||pb_ck(\"tduid3\",0,2592E3),sessionStorage.setItem(\"pb_sn\",\"1\")));\n",["escape",["macro",109],8,16],"\u0026\u0026\"0\"!=",["escape",["macro",109],8,16],"\u0026\u0026\"Sale\"==",["escape",["macro",8],8,16],"\u0026\u0026(dataLayer.push({event:\"GAevent\",eventCategory:\"Enhanced Ecommerce\",eventAction:\"pb campaign sale\",eventLabel:",["escape",["macro",7],8,16],",eventValue:",["escape",["macro",69],8,16],"}),pb_ck(\"tduid3\",0,0));\u003C\/script\u003E\n"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":81
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_searchResultList\"\u003E(function(){if(\"onlineshop\"==",["escape",["macro",14],8,16],"\u0026\u0026\"Search\"==",["escape",["macro",35],8,16],")if(20\u003E",["escape",["macro",140],8,16],".length)dataLayer.push({event:\"listView\",channel:\"onlineshop\",currencyCode:\"EUR\",impressions:",["escape",["macro",140],8,16],"});else{var a=",["escape",["macro",140],8,16],".slice(0,20);dataLayer.push({event:\"listView\",channel:\"onlineshop\",currencyCode:\"EUR\",impressions:a});dataLayer.push({impressions:void 0});a=",["escape",["macro",140],8,16],".slice(20);dataLayer.push({event:\"listView_part2\",channel:\"onlineshop\",currencyCode:\"EUR\",\nimpressions:a})}})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":114
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_moebel_sale\"\u003Evar _mo=_mo||[];_mo.push([\"_key\",\"21e55062-f619-458f-9eb6-9e7c5eb9b17c\"]);_mo.push([\"_umsatz\",\"",["escape",["macro",64],7],"\"]);_mo.push([\"_versandkosten\",\"\"]);_mo.push([\"_artikelliste\",\"\"]);(function(){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"https:\/\/sales1.moebel.de\/asyndic.js\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":141
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript id=\"gtmctagid_moebel_setCookie\" type=\"text\/gtmscript\"\u003Eif(\"moebel_de\"==",["escape",["macro",18],8,16],"){var cookieName=\"coopPartner\",cookieValue=\"moebel.de\",expirationTime=604800;expirationTime*=1E3;var date=new Date,dateTimeNow=date.getTime();date.setTime(dateTimeNow+expirationTime);date=date.toUTCString();document.cookie=cookieName+\"\\x3d\"+cookieValue+\"; expires\\x3d\"+date+\"; path\\x3d\/; domain\\x3d.\"+location.hostname.replace(\/^www\\.\/i,\"\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":142
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_abtestactivator\"\u003Evoid 0!==",["escape",["macro",58],8,16],"\u0026\u00261==\/(6bccpghgQTSm1DSQetMQ_A.*)\/.test(",["escape",["macro",58],8,16],".join(\"!\"))\u0026\u0026dataLayer.push({event:\"optimize.activate\"});\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":159
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript id=\"gtmctagid_salewithinsurance\" type=\"text\/gtmscript\"\u003E(function(){var a=document.getElementById(\"s_plugin_container\");\"undefined\"!=typeof a\u0026\u0026null!=a\u0026\u0026\"s_active\"==a.className\u0026\u0026dataLayer.push({event:\"GAevent\",eventCategory:\"engagement\",eventAction:\"insurance sale\",eventLabel:document.getElementsByClassName(\"s_period\")[0].innerText})})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":161
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_documentlocationsaver\"\u003EsessionStorage.setItem(\"ga_dl\",",["escape",["macro",57],8,16],");\u003C\/script\u003E\n"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":163
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript data-gtmsrc=\"https:\/\/www.youtube.com\/iframe_api\" type=\"text\/gtmscript\"\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":166
    },{
      "function":"__html",
      "metadata":["map"],
      "setup_tags":["list",["tag",58,1]],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_pinterest_maintag\"\u003E(function(){if(\"pageView\"==",["escape",["macro",8],8,16],"\u0026\u0026\"Category\"==",["escape",["macro",35],8,16],")pintrk(\"track\",\"viewcategory\");else if(\"addToCart\"==",["escape",["macro",8],8,16],")pintrk(\"track\",\"AddToCart\",{value:",["escape",["macro",36],8,16],".offers[0].price,order_quantity:",["escape",["macro",36],8,16],".offers[0].amount,currency:\"EUR\"});else if(\"Sale\"==",["escape",["macro",8],8,16],"){for(var b=",["escape",["macro",0],8,16],".cart,d=[],a=0;a\u003Cb.length;a++)d.push({product_name:b[a].name,product_id:b[a].ean,product_price:b[a].offers[0].price,product_quantity:b[a].offers[0].amount});\na=function(){for(var a=0,c=0;c\u003Cb.length;c++)a+=b[c].offers[0].amount;return a};var e=function(){for(var a=0,c=0;c\u003Cb.length;c++)a+=b[c].offers[0].amount*b[c].offers[0].price;return a};d={value:e,order_quantity:a,currency:\"EUR\",line_items:d};pintrk(\"track\",\"checkout\",d)}else\"Item\"==",["escape",["macro",35],8,16],"?pintrk(\"track\",\"pagevisit\"):\"pageView\"==",["escape",["macro",8],8,16],"\u0026\u0026\"Search\"==",["escape",["macro",35],8,16],"\u0026\u0026pintrk(\"track\",\"search\",{search_query:\"",["escape",["macro",50],7],"\"})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":173
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\" id=\"gtmctagid_pinterest_setuptag\"\u003E(function(){\"undefined\"==typeof window.pintrk\u0026\u0026(!function(b){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var a=window.pintrk;a.queue=[];a.version=\"3.0\";a=document.createElement(\"script\");a.async=!0;a.src=b;b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)}}(\"https:\/\/s.pinimg.com\/ct\/core.js\"),pintrk(\"load\",\"2613177073704\"),pintrk(\"page\"))})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":180
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"Sale"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"addToCart"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"removeFromCart"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"pageView"
    },{
      "function":"_eq",
      "arg0":["macro",14],
      "arg1":"efood"
    },{
      "function":"_re",
      "arg0":["macro",68],
      "arg1":".*"
    },{
      "function":"_re",
      "arg0":["macro",68],
      "arg1":"(^addToCart$)|(^removeFromCart$)|(^Sale$)|(^bannerView$)|(^bannerClick$)|(^promoView$)|(^promoClick$)|(^listView$)|(^listView_part2$)|(^listClick$)"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"GAevent"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"navigation"
    },{
      "function":"_eq",
      "arg0":["macro",9],
      "arg1":"click outbound link"
    },{
      "function":"_cn",
      "arg0":["macro",14],
      "arg1":"onlineshop"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"GAEvent"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"registerCustomer"
    },{
      "function":"_eq",
      "arg0":["macro",14],
      "arg1":"onlineshop"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.pageError"
    },{
      "function":"_eq",
      "arg0":["macro",35],
      "arg1":"Item"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.video"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_643($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_646($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",131],
      "arg1":"_account -has-icon rosso_modal_open"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.linkClick"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_705($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.elementVisibility"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_730($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",131],
      "arg1":"read-more"
    },{
      "function":"_cn",
      "arg0":["macro",80],
      "arg1":"onlineshop\/product"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.click"
    },{
      "function":"_cn",
      "arg0":["macro",80],
      "arg1":"pro\/zahlung-erfolgreich\/"
    },{
      "function":"_sw",
      "arg0":["macro",31],
      "arg1":"\/realtv"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.scrollDepth"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_780($|,)))"
    },{
      "function":"_sw",
      "arg0":["macro",81],
      "arg1":"\/realtv\/"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.js"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"optimize.activate"
    },{
      "function":"_eq",
      "arg0":["macro",31],
      "arg1":"\/fernseher\/"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_879($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",127],
      "arg1":"(^$|((^|,)6178770_895($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.dom"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.load"
    },{
      "function":"_cn",
      "arg0":["macro",9],
      "arg1":"video spot click"
    },{
      "function":"_css",
      "arg0":["macro",133],
      "arg1":"a.register_link"
    },{
      "function":"_css",
      "arg0":["macro",133],
      "arg1":"a.cancel_button.cancelButton"
    },{
      "function":"_eq",
      "arg0":["macro",14],
      "arg1":"instore"
    },{
      "function":"_re",
      "arg0":["macro",68],
      "arg1":"pageView"
    },{
      "function":"_re",
      "arg0":["macro",80],
      "arg1":"\\\/newsletter\\\/bestaetigung|\\\/newsletter\\\/abmeldung"
    },{
      "function":"_eq",
      "arg0":["macro",134],
      "arg1":"popstate"
    },{
      "function":"_sw",
      "arg0":["macro",31],
      "arg1":"\/markt\/wochenprospekte\/"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"gtm.historyChange"
    },{
      "function":"_eq",
      "arg0":["macro",61],
      "arg1":"true"
    },{
      "function":"_eq",
      "arg0":["macro",41],
      "arg1":"1"
    },{
      "function":"_eq",
      "arg0":["macro",35],
      "arg1":"Search"
    },{
      "function":"_eq",
      "arg0":["macro",141],
      "arg1":"moebel.de"
    },{
      "function":"_eq",
      "arg0":["macro",18],
      "arg1":"moebel_de"
    },{
      "function":"_eq",
      "arg0":["macro",141],
      "arg1":"undefined"
    },{
      "function":"_cn",
      "arg0":["macro",142],
      "arg1":"payment_method"
    },{
      "function":"_eq",
      "arg0":["macro",56],
      "arg1":"reload"
    },{
      "function":"_sw",
      "arg0":["macro",31],
      "arg1":"\/pro\/"
    }],
  "rules":[
    [["if",0],["add",0,1,9,10,39,40,49]],
    [["if",1],["add",1,39]],
    [["if",2],["add",1]],
    [["if",3],["add",1,3,11,12,39,53]],
    [["if",6],["add",2]],
    [["if",7],["add",2,39,44]],
    [["if",8,9,10,11],["add",2]],
    [["if",12],["add",4]],
    [["if",0,13],["add",5,43,46,57]],
    [["if",14],["add",6]],
    [["if",3,15],["add",7]],
    [["if",0,4],["add",8]],
    [["if",16,17],["add",13]],
    [["if",16,18],["add",14]],
    [["if",10,19,20,21],["add",15]],
    [["if",22,23],["add",16]],
    [["if",24,25,26],["add",17]],
    [["if",3,27],["add",18]],
    [["if",28,29,30],["add",19]],
    [["if",31,32],["add",20]],
    [["if",33],["add",21]],
    [["if",22,34,35],["add",22]],
    [["if",13,15,22,36],["add",23]],
    [["if",32],["add",24,25,26,27,30,31,32,34,35,36,37,38]],
    [["if",37],["add",28,29,47]],
    [["if",38],["add",33]],
    [["if",26,40],["add",41]],
    [["if",26,41],["add",42]],
    [["if",3,13],["add",43,57]],
    [["if",42,43],["add",43]],
    [["if",0,42],["add",43]],
    [["if",3,44],["add",45]],
    [["if",45,47],["unless",46],["add",47]],
    [["if",3,48],["add",48]],
    [["if",3],["unless",49],["add",49]],
    [["if",3,13,50],["add",50]],
    [["if",0,13,51],["add",51]],
    [["if",3,13,52,53],["add",52]],
    [["if",26,54],["add",54]],
    [["if",37,48],["unless",55],["add",55]],
    [["if",3,56],["add",56]],
    [["if",1,10],["add",57]],
    [["if",4,5],["block",1,53]],
    [["if",3,4],["block",1]],
    [["if",7,39],["block",39]]]
}