data = {
"resource": {
  "version":"125",
  "macros":[{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=document.referrer.split(\".com\");return a[1]}catch(b){return\"\"}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=new Date,c=-a.getTimezoneOffset(),d=0\u003C=c?\"+\":\"-\",b=function(a){a=Math.abs(Math.floor(a));return(10\u003Ea?\"0\":\"\")+a};return a.getFullYear()+\"-\"+b(a.getMonth()+1)+\"-\"+b(a.getDate())+\"T\"+b(a.getHours())+\":\"+b(a.getMinutes())+\":\"+b(a.getSeconds())+\".\"+b(a.getMilliseconds())+d+b(c\/60)+\":\"+b(c%60)})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{return window.location.href.split(\"\/\").pop()}catch(a){}})();"]
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"email",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"email"
    },{
      "function":"__k",
      "vtp_decodeCookie":true,
      "vtp_name":"mm_cookie_email"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return ",["escape",["macro",3],8,16],"||",["escape",["macro",4],8,16],"||",["escape",["macro",5],8,16],"})();"]
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",7],8,16],".length?\"\\x26\"+",["escape",["macro",7],8,16],":\"\";a=a.length?\"?\"+a.replace(\/\u0026[^\u0026@]+@[^\u0026]+\/g,\"\").substring(1):\"\";return 1\u003E=a.length?\"\":a})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return function(d,e,f,b,c){if(d\u0026\u0026e){b=b?\"; path\\x3d\"+b:\"\";c=c?\"; domain\\x3d\"+c:\"\";var a=\"\";f\u0026\u0026(a=new Date,a.setTime(a.getTime()+f),a=\"; expires\\x3d\"+a.toUTCString());document.cookie=d+\"\\x3d\"+e+a+b+c}}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{return{ecommerce:{purchase:{actionField:{id:_thrive_order.order.id,affiliation:\"\",revenue:_thrive_order.order.total_readable,tax:\"0.00\",shipping:\"0.00\",coupon:\"\"},products:[{name:_thrive_order.order.product.name,id:_thrive_order.order.product.id,price:_thrive_order.order.product.total_readable,brand:\"Measureschool\",category:\"Membership\",quantity:1,coupon:\"\"}]}}}}catch(a){}})();"]
    },{
      "function":"__e"
    },{
      "function":"__dbg"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"cid"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"cid",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"cid"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",13],8,16],"||",["escape",["macro",14],8,16],";if(a)return ",["escape",["macro",9],8,16],"(\"cid\",a,2592E6,\"\/\"),a;if(",["escape",["macro",15],8,16],")return ",["escape",["macro",15],8,16],"})();"]
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":["macro",12],
      "vtp_fieldsToSet":["list",["map","fieldName","userId","value",["macro",16]],["map","fieldName","page","value",["template",["macro",17],["macro",8]]]],
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":true,
      "vtp_autoLinkDomains":"measureschool.com, thrivecart.com, measure.school",
      "vtp_enableLinkId":false,
      "vtp_dimension":["list",["map","index","1","dimension",["macro",16]]],
      "vtp_enableEcommerce":false,
      "vtp_trackingId":"UA-58541733-2",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"optinpage",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__r"
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__j",
      "vtp_name":"_thrive_order.order.id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"timeToSerp"
    },{
      "function":"__cid"
    },{
      "function":"__hid"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ecommerce.purchase.actionField.revenue"
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"firstName"
    },{
      "function":"__v",
      "vtp_name":"gtm.triggers",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":""
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_source",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"rid",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"firstName",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__v",
      "vtp_name":"gtm.newUrlFragment",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.historyChangeSource",
      "vtp_dataLayerVersion":1
    },{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_name":"gtm.oldUrlFragment",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"gtm.start"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"affiliate",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"singUpDate"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"optin",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"username",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__smm",
      "vtp_setDefaultValue":false,
      "vtp_input":["macro",0],
      "vtp_map":["list",["map","key","\/guide\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/GTMTraining-ResourceGuide-1.pdf"],["map","key","\/sourcecookie\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/sourcecookietemplate.zip"],["map","key","\/vwo\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/vwo.zip"],["map","key","\/tagplan\/","value","https:\/\/docs.google.com\/spreadsheets\/d\/1phSvWwTe8in1IB6x9ekqi2nOxvjhpcbl2Hw5Hz5rwok\/edit?usp=sharing"],["map","key","\/eventtrackingdemo\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/eventtrackingcourse.zip"],["map","key","\/emailinput\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/emailInput.zip"],["map","key","\/cookieswitch\/","value","http:\/\/measureschool.com\/wp-content\/uploads\/2016\/02\/gtmtraining-cookieswitch.zip"]]
    },{
      "function":"__d",
      "vtp_elementSelector":"form input[name=\"field[19]\"]",
      "vtp_selectorType":"CSS"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"premiumSupport"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"purchase"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"price"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"coupon"
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"transaction_key",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__k",
      "vtp_decodeCookie":false,
      "vtp_name":"userId"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"member"
    },{
      "function":"__u",
      "vtp_component":"FRAGMENT",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"answer",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"coupon",
      "vtp_enableMultiQueryKeys":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ecommerce.purchase.actionfield.id"
    },{
      "function":"__v",
      "vtp_name":"gtm.element",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementClasses",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementId",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementUrl",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.element",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementClasses",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementId",
      "vtp_dataLayerVersion":1
    },{
      "function":"__ctv"
    },{
      "function":"__r"
    }],
  "tags":[{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",18],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":5
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":true,
      "vtp_useEcommerceDataLayer":false,
      "vtp_ecommerceMacroData":["macro",10],
      "vtp_eventCategory":"EE",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",18],
      "vtp_eventAction":"Transaction",
      "vtp_eventLabel":"Purchase",
      "vtp_enableEcommerce":true,
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_ecommerceIsEnabled":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":11
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":true,
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_eventCategory":"Signup",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_enableLinkId":false,
      "vtp_gaSettings":["macro",18],
      "vtp_eventAction":"Email Signup",
      "vtp_eventLabel":["macro",19],
      "vtp_enableEcommerce":false,
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":27
    },{
      "function":"__opt",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_optimizeContainerId":"GTM-KWBXSG3",
      "vtp_gaSettings":["macro",18],
      "tag_id":41
    },{
      "function":"__img",
      "once_per_event":true,
      "vtp_useCacheBuster":true,
      "vtp_url":["template","https:\/\/script.google.com\/macros\/s\/AKfycbwyIYpZgpq1wwb7Phk5RjvaN40WXZr34xfnvQNcyfOeS3BBjl8\/exec?email=",["escape",["macro",6],12],"\u0026event=downloaded\u0026eventdata=",["escape",["macro",2],12]],
      "vtp_cacheBusterQueryParam":"gtmcb",
      "vtp_randomNumber":["macro",21],
      "tag_id":43
    },{
      "function":"__paused",
      "vtp_originalTagType":"html",
      "tag_id":54
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":"404 Error",
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",18],
      "vtp_eventAction":["macro",17],
      "vtp_eventLabel":["macro",22],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":56
    },{
      "function":"__img",
      "once_per_event":true,
      "vtp_useCacheBuster":true,
      "vtp_url":["template","https:\/\/script.google.com\/macros\/s\/AKfycbwvGEu9CQYCKu3ESGhtAiSbkO5FnV6RrvrQwyiwks-WhM9S0-u2\/exec?ContactId=",["escape",["macro",15],12],"\u0026OrderId=",["escape",["macro",23],12]],
      "vtp_cacheBusterQueryParam":"gtmcb",
      "vtp_randomNumber":["macro",21],
      "tag_id":58
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":true,
      "vtp_useEcommerceDataLayer":true,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",18],
      "vtp_enableEcommerce":true,
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_ecommerceIsEnabled":true,
      "tag_id":59
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_TIMING",
      "vtp_timingCategory":"SERP Bounce",
      "vtp_gaSettings":["macro",18],
      "vtp_timingVar":["macro",20],
      "vtp_timingValue":["macro",24],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsTiming":true,
      "tag_id":62
    },{
      "function":"__fsl",
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"1927886_24",
      "tag_id":66
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"1927886_26",
      "tag_id":67
    },{
      "function":"__lcl",
      "vtp_waitForTags":false,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"1927886_36",
      "tag_id":68
    },{
      "function":"__evl",
      "vtp_elementId":"payment-processor-wrap",
      "vtp_useOnScreenDuration":false,
      "vtp_useDomChangeListener":true,
      "vtp_firingFrequency":"ONCE",
      "vtp_selectorType":"ID",
      "vtp_onScreenRatio":"50",
      "vtp_uniqueTriggerId":"1927886_105",
      "tag_id":69
    },{
      "function":"__hl",
      "tag_id":70
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E(function(a,d,e,f,g,b,c){a.prismGlobalObjectAlias=f;a.pgo=a.pgo||function(){(a.pgo.q=a.pgo.q||[]).push(arguments)};a.pgo.l=(new Date).getTime();b=d.createElement(\"script\");b.src=e;b.async=!0;c=d.getElementsByTagName(\"script\")[0];c.parentNode.insertBefore(b,c)})(window,document,\"https:\/\/prism.app-us1.com\/prism.js\",\"pgo\");pgo(\"setAccount\",\"251578439\");pgo(\"setTrackByDefault\",!0);pgo(\"process\");\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":6
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E!function(b,e,f,g,a,c,d){b.fbq||(a=b.fbq=function(){a.callMethod?a.callMethod.apply(a,arguments):a.queue.push(arguments)},b._fbq||(b._fbq=a),a.push=a,a.loaded=!0,a.version=\"2.0\",a.queue=[],c=e.createElement(f),c.async=!0,c.src=g,d=e.getElementsByTagName(f)[0],d.parentNode.insertBefore(c,d))}(window,document,\"script\",\"https:\/\/connect.facebook.net\/en_US\/fbevents.js\");fbq(\"init\",\"216233405400796\");fbq(\"track\",\"PageView\");window.google_tag_manager[",["escape",["macro",25],8,16],"].onHtmlSuccess(",["escape",["macro",26],8,16],");\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":12
    },{
      "function":"__html",
      "setup_tags":["list",["tag",16,0]],
      "once_per_event":true,
      "vtp_html":["template","\n\u003Cscript type=\"text\/gtmscript\"\u003E-1==document.location.href.search(\"appspot.com\")\u0026\u0026fbq(\"track\",\"Purchase\",{value:\"",["escape",["macro",27],7],"\",currency:\"USD\"});\u003C\/script\u003E\n\n"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":13
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript data-gtmsrc=\"\/\/platform.twitter.com\/oct.js\" type=\"text\/gtmscript\"\u003E\u003C\/script\u003E\n\u003Cscript type=\"text\/gtmscript\"\u003Etwttr.conversion.trackPid(\"numle\",{tw_sale_amount:0,tw_order_quantity:0});\u003C\/script\u003E\n\u003Cnoscript\u003E\n\u003Cimg height=\"1\" width=\"1\" style=\"display:none;\" alt=\"\" src=\"https:\/\/analytics.twitter.com\/i\/adsct?txn_id=numle\u0026amp;p_id=Twitter\u0026amp;tw_sale_amount=0\u0026amp;tw_order_quantity=0\"\u003E\n\u003Cimg height=\"1\" width=\"1\" style=\"display:none;\" alt=\"\" src=\"\/\/t.co\/i\/adsct?txn_id=numle\u0026amp;p_id=Twitter\u0026amp;tw_sale_amount=0\u0026amp;tw_order_quantity=0\"\u003E\n\u003C\/noscript\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":18
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003E(function(a,c,e,f,d,b){a.hj=a.hj||function(){(a.hj.q=a.hj.q||[]).push(arguments)};a._hjSettings={hjid:78276,hjsv:5};d=c.getElementsByTagName(\"head\")[0];b=c.createElement(\"script\");b.async=1;b.src=e+a._hjSettings.hjid+f+a._hjSettings.hjsv;d.appendChild(b)})(window,document,\"\/\/static.hotjar.com\/c\/hotjar-\",\".js?sv\\x3d\");\u003C\/script\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":19
    },{
      "function":"__html",
      "setup_tags":["list",["tag",16,0]],
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003E-1==document.location.href.search(\"appspot.com\")\u0026\u0026fbq(\"track\",\"Sign Up\");\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":22
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E!function(b,c,a){window.HSCW=c;window.HS=a;a.beacon=a.beacon||{};a=a.beacon;a.userConfig={};a.readyQueue=[];a.config=function(a){this.userConfig=a};a.ready=function(a){this.readyQueue.push(a)};c.config={docs:{enabled:!1,baseUrl:\"\"},contact:{enabled:!0,formId:\"2b055f6f-61ed-11e6-91aa-0a5fecc78a4d\"}};c=b.getElementsByTagName(\"script\")[0];b=b.createElement(\"script\");b.type=\"text\/javascript\";b.async=!0;b.src=\"https:\/\/djtflbt20bdde.cloudfront.net\/\";c.parentNode.insertBefore(b,c)}(document,window.HSCW||\n{},window.HS||{});\u003C\/script\u003E\n\n\u003Cscript type=\"text\/gtmscript\"\u003EHS.beacon.config({icon:\"message\",color:\"#7f8c8d\",instructions:\"Got a question? If you leave it in the comment section everyone can benefit from an answer. Want to discuss something privately? No problem, leave us a message below\"});",["escape",["macro",4],8,16],"\u0026\u0026HS.beacon.ready(function(){HS.beacon.identify({name:",["escape",["macro",29],8,16],",email:\"",["escape",["macro",4],7],"\",userID:",["escape",["macro",16],8,16],"})});\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":37
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){try{jQuery(\"input[name\\x3d'field[12]']\").length\u0026\u0026jQuery(\"input[name\\x3d'field[12]']\").val(",["escape",["macro",31],8,16],")}catch(a){return a}})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":42
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{jQuery(document).ready(function(){var b=jQuery('a[href*\\x3d\"thrivecart\"]');b.each(function(b,c){var a=jQuery(c),d=a.attr(\"href\");-1!=d.indexOf(\"?\")?a.attr(\"href\",jQuery(a).attr(\"href\")+\"\\x26cid\\x3d",["escape",["macro",16],7],"\"):a.attr(\"href\",jQuery(a).attr(\"href\")+\"?cid\\x3d",["escape",["macro",16],7],"\")})})}catch(b){};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":45
    },{
      "function":"__html",
      "setup_tags":["list",["tag",16,0]],
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E-1==document.location.href.search(\"appspot.com\")\u0026\u0026fbq(\"track\",\"Checkout\");\u003C\/script\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":47
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\n\u003Cscript type=\"text\/gtmscript\"\u003E(function(d,b,a){(b[a]=b[a]||[]).push(function(){try{b.yaCounter45107106=new Ya.Metrika({id:45107106,clickmap:!0,trackLinks:!0,accurateTrackBounce:!0,webvisor:!0,ecommerce:\"dataLayer\"})}catch(f){}});var e=d.getElementsByTagName(\"script\")[0],c=d.createElement(\"script\");a=function(){e.parentNode.insertBefore(c,e)};c.type=\"text\/javascript\";c.async=!0;c.src=\"https:\/\/mc.yandex.ru\/metrika\/watch.js\";\"[object Opera]\"==b.opera?d.addEventListener(\"DOMContentLoaded\",a,!1):a()})(document,window,\"yandex_metrika_callbacks\");\u003C\/script\u003E\n",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":49
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"  \u003Cscript data-version=\"v1\" data-widget-id=\"measureschool\" id=\"toastersurvey\" type=\"text\/gtmscript\"\u003E!function(){function c(){var b=document.createElement(\"script\");b.type=\"text\/javascript\";b.async=!0;var a=\"https:\/\/measureschool.com\/wp-content\/themes\/generatepress_child\/js\/survey.js\";b.src=a+(0\u003C=a.indexOf(\"?\")?\"\\x26\":\"?\")+\"ref\\x3d\"+encodeURIComponent(window.location.href);a=document.getElementById(\"toastersurvey\");a.parentNode.insertBefore(b,a)}window.attachEvent?window.attachEvent(\"onload\",c):window.addEventListener(\"load\",c,!1)}();\u003C\/script\u003E\n\u003Clink rel=\"stylesheet\" href=\"https:\/\/maxcdn.bootstrapcdn.com\/bootstrap\/3.3.7\/css\/bootstrap.min.css\"\u003E\n\u003Cstyle\u003E.choice,h5{display:block}.container{margin-top:20px}#slideout{background:#fff;box-shadow:0 0 5px rgba(0,0,0,.3);color:#333;position:fixed;bottom:-500px;right:5%;width:250px;padding-bottom:10px;-webkit-transition-duration:.3s;-moz-transition-duration:.3s;-o-transition-duration:.3s;transition-duration:.3s}#slideout.on{bottom:0}.choice{margin:5px auto;width:80%}h5{text-align:center}#slideout .glyphicon{display:block;margin:3px;text-align:right;color:grey}#thankyou{display:none}\u003C\/style\u003E \n \u003Cdiv id=\"slideout\"\u003E\n      \u003Ca href=\"\" id=\"hide\"\u003E\u003Cspan class=\"glyphicon glyphicon-remove-circle\"\u003E\u003C\/span\u003E\u003C\/a\u003E\n      \u003Cdiv id=\"questions\"\u003E\u003C\/div\u003E\n    \u003Cdiv id=\"thankyou\"\u003E\n      \u003Ch5\u003EThanks! Your answer was recorded.\u003C\/h5\u003E\n    \u003C\/div\u003E\n  \u003C\/div\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":51
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E",["escape",["macro",33],8,16],"\u0026\u0026(document.querySelector(\"input[data-field\\x3d'fullname']\").value=",["escape",["macro",33],8,16],");",["escape",["macro",3],8,16],"\u0026\u0026(document.querySelector(\"input[data-field\\x3d'email']\").value=",["escape",["macro",3],8,16],");\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":53
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Evar dataLayer=window.dataLayer||[];dataLayer.push({event:\"checkoutStep\",ecommerce:{checkout:{actionField:{step:\"2\",option:\"\"}}}});\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":60
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=document.location.search,c=document.location.hash,b=",["escape",["macro",36],8,16],",d=",["escape",["macro",34],8,16],",e=",["escape",["macro",37],8,16],";window.history\u0026\u0026(\"gtm.js\"===b\u0026\u0026-1\u003Cdocument.referrer.indexOf(\"www.google.\")\u0026\u0026-1===a.indexOf(\"gclid\")\u0026\u0026-1===a.indexOf(\"utm_\")\u0026\u0026\"#gref\"!==c?(window.oldFragment=!1,window.history.pushState(null,null,\"#gref\")):\"gtm.js\"===b\u0026\u0026(window.oldFragment=!0),\"gtm.historyChange\"===b\u0026\u0026\"\"===d\u0026\u0026\"gref\"===e\u0026\u0026(a=(new Date).getTime()-",["escape",["macro",38],8,16],",window.oldFragment?window.history.go(-1):\ndataLayer.push({event:\"returnToSerp\",timeToSerp:a,eventCallback:function(){window.history.go(-1)}})))})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":61
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E",["escape",["macro",9],8,16],"(\"tc_affiliate_measureschool\",",["escape",["macro",39],8,16],",2592E6,\"\/\",\".measureschool.com\");\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":63
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow.intercomSettings={app_id:\"rcrgvglk\",email:",["escape",["macro",4],8,16],",name:",["escape",["macro",29],8,16],",user_id:",["escape",["macro",13],8,16],"};\u003C\/script\u003E\n\u003Cscript type=\"text\/gtmscript\"\u003E(function(){function e(){var c=f.createElement(\"script\");c.type=\"text\/javascript\";c.async=!0;c.src=\"https:\/\/widget.intercom.io\/widget\/key\";var a=f.getElementsByTagName(\"script\")[0];a.parentNode.insertBefore(c,a)}var a=window,d=a.Intercom;if(\"function\"===typeof d)d(\"reattach_activator\"),d(\"update\",intercomSettings);else{var f=document,b=function(){b.c(arguments)};b.q=[];b.c=function(a){b.q.push(a)};a.Intercom=b;a.attachEvent?a.attachEvent(\"onload\",e):a.addEventListener(\"load\",e,!1)}})();\u003C\/script\u003E\n\u003Cstyle\u003E#intercom-container { display:none; }\u003C\/style\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":64
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow.retainlySettings={app_id:\"5be534ef74643\",email:",["escape",["macro",4],8,16],",name:",["escape",["macro",29],8,16],",signedup_at:\"",["escape",["macro",40],7],"\"};\u003C\/script\u003E\n\u003Cscript type=\"text\/gtmscript\"\u003E(function(){function d(){var b=e.createElement(\"script\");b.type=\"text\/javascript\";b.async=!0;b.src=\"https:\/\/retainly.co\/app\/getjs\/retainly\/5be534ef74643\";var a=e.getElementsByTagName(\"script\")[0];a.parentNode.insertBefore(b,a)}var c=window,e=document,a=function(){a.c(arguments)};a.q=[];a.c=function(b){a.q.push(b)};c.retainly=a;c.attachEvent?c.attachEvent(\"onload\",d):c.addEventListener(\"load\",d,!1)})();Identify();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":65
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"gtm.js"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"purchase"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"signup"
    },{
      "function":"_cn",
      "arg0":["macro",20],
      "arg1":"\/download\/?"
    },{
      "function":"_cn",
      "arg0":["macro",4],
      "arg1":"@"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"user"
    },{
      "function":"_cn",
      "arg0":["macro",17],
      "arg1":"\/video\/"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"gtm.dom"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"404"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"checkoutStep"
    },{
      "function":"_lt",
      "arg0":["macro",24],
      "arg1":"18000000"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"returnToSerp"
    },{
      "function":"_cn",
      "arg0":["macro",20],
      "arg1":"measureschool"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"membersignup"
    },{
      "function":"_eq",
      "arg0":["macro",28],
      "arg1":"measure.school"
    },{
      "function":"_cn",
      "arg0":["macro",17],
      "arg1":"\/lp\/"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"gtm.formSubmit"
    },{
      "function":"_re",
      "arg0":["macro",30],
      "arg1":"(^$|((^|,)1927886_24($|,)))"
    },{
      "function":"_cn",
      "arg0":["macro",20],
      "arg1":"\/lp\/"
    },{
      "function":"_eq",
      "arg0":["macro",16],
      "arg1":"undefined"
    },{
      "function":"_eq",
      "arg0":["macro",32],
      "arg1":"undefined"
    },{
      "function":"_cn",
      "arg0":["macro",20],
      "arg1":"acid="
    },{
      "function":"_cn",
      "arg0":["macro",20],
      "arg1":"you-are-now-signed-up"
    },{
      "function":"_eq",
      "arg0":["macro",3],
      "arg1":"undefined"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"gtm.elementVisibility"
    },{
      "function":"_re",
      "arg0":["macro",30],
      "arg1":"(^$|((^|,)1927886_105($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",34],
      "arg1":"^$"
    },{
      "function":"_eq",
      "arg0":["macro",35],
      "arg1":"popstate"
    },{
      "function":"_eq",
      "arg0":["macro",11],
      "arg1":"gtm.historyChange"
    },{
      "function":"_eq",
      "arg0":["macro",39],
      "arg1":"undefined"
    },{
      "function":"_re",
      "arg0":["macro",13],
      "arg1":"^$"
    },{
      "function":"_cn",
      "arg0":["macro",28],
      "arg1":"measure.school"
    }],
  "rules":[
    [["if",0],["add",0,3,15,16,18,19,25,29,10,12,13,14]],
    [["if",1],["add",1,7,17,21]],
    [["if",2],["add",2,20]],
    [["if",3,4,5],["add",4]],
    [["if",6,7],["add",5]],
    [["if",8],["add",6]],
    [["if",9],["add",8]],
    [["if",10,11],["add",9]],
    [["if",0,12],["add",11]],
    [["if",13],["add",20]],
    [["if",7,14],["add",21]],
    [["if",0,15],["add",21]],
    [["if",16,17],["add",22]],
    [["if",7,18],["unless",19],["add",23]],
    [["if",5],["unless",20],["add",24]],
    [["if",0,21],["unless",22],["add",26]],
    [["if",7],["unless",23],["add",27]],
    [["if",24,25],["add",28]],
    [["if",26,27,28],["add",29]],
    [["if",0],["unless",29],["add",30]],
    [["if",0,31],["unless",30],["add",31,32]]]
}