data = {
"resource": {
  "version":"8",
  "macros":[{
      "function":"__e"
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",1],
      "vtp_fullMatch":false,
      "vtp_replaceAfterMatch":false,
      "vtp_defaultValue":"staging",
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key","marketingplatform\\.google\\.com\\\/about\\\/partner.*","value","gmp partners"],["map","key","marketingplatform\\.google\\.com\\\/about.*","value","gmp"],["map","key","admanager\\.google\\.com.*","value","gam"],["map","key","measurementpartners\\.google\\.com.*","value","mm partners"]]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":["macro",2],
      "vtp_name":"siteName"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventCategory"
    },{
      "function":"__u",
      "vtp_component":"PROTOCOL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__c",
      "vtp_value":["template",["macro",5],":\/\/",["macro",6]]
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",1],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_defaultValue":"",
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key",".*(\u0026|\\?)(dclid=[^\u0026]*).*","value","$2\u0026"]]
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",1],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_defaultValue":"",
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key","..*(\u0026|\\?)(gclid=[^\u0026]*).*","value","$2\u0026"]]
    },{
      "function":"__c",
      "vtp_value":["template",["macro",9],["macro",10]]
    },{
      "function":"__remm",
      "vtp_setDefaultValue":false,
      "vtp_input":["macro",11],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key","(.+)\u0026","value","?$1"]]
    },{
      "function":"__c",
      "vtp_value":["template",["macro",7],["macro",8],["macro",12]]
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",1],
      "vtp_fullMatch":false,
      "vtp_replaceAfterMatch":false,
      "vtp_ignoreCase":true,
      "vtp_defaultValue":["macro",3],
      "vtp_map":["list",["map","key",".*(.\\.appspot\\.com|staging).*","value","staging"]]
    },{
      "function":"__f",
      "vtp_component":"URL"
    },{
      "function":"__remm",
      "vtp_setDefaultValue":false,
      "vtp_input":["macro",15],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key","(.*\/\/[^\\?\\#]*).*","value","$1"]]
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",15],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_ignoreCase":true,
      "vtp_defaultValue":["macro",16],
      "vtp_map":["list",["map","key",".*admanager\\.google\\.com\\\/home.*","value",""]]
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",15],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_ignoreCase":true,
      "vtp_defaultValue":["macro",16],
      "vtp_map":["list",["map","key",".*marketingplatform\\.google\\.com\\\/about.*","value",""]]
    },{
      "function":"__smm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",14],
      "vtp_defaultValue":["macro",16],
      "vtp_map":["list",["map","key","gam","value",["macro",17]],["map","key","gmp partners","value",["macro",18]],["map","key","gmp","value",["macro",18]]]
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_source",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_medium",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_content",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_campaign",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"QUERY",
      "vtp_queryKey":"utm_term",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"country"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"region"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"language"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"pageName"
    },{
      "function":"__c",
      "vtp_value":["template",["macro",3],": ",["macro",28]]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"resType"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"resProduct"
    },{
      "function":"__remm",
      "vtp_setDefaultValue":false,
      "vtp_input":["macro",1],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key",".+utm\\_source.+","value","utms"],["map","key",".+utm\\_medium.+","value","utms"],["map","key",".+gclid\\=.+","value","autotag"],["map","key",".+dclid\\=.+","value","autotag"]]
    },{
      "function":"__u",
      "convert_case_to":1,
      "vtp_component":"QUERY",
      "vtp_queryKey":"icid",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__remm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",14],
      "vtp_fullMatch":true,
      "vtp_replaceAfterMatch":true,
      "vtp_defaultValue":"UA-118666886-4",
      "vtp_ignoreCase":true,
      "vtp_map":["list",["map","key","gmp(.partners)?","value","UA-38676921-23"],["map","key","gam","value","UA-118666886-2"],["map","key","mm partners","value","UA-118666886-5"]]
    },{
      "function":"__gas",
      "vtp_cookieDomain":"auto",
      "vtp_doubleClick":false,
      "vtp_setTrackerName":false,
      "vtp_useDebugVersion":false,
      "vtp_fieldsToSet":["list",["map","fieldName","allowLinker","value","true"],["map","fieldName","anonymizeIp","value","true"],["map","fieldName","location","value",["macro",13]],["map","fieldName","referrer","value",["macro",19]],["map","fieldName","campaignSource","value",["macro",20]],["map","fieldName","campaignMedium","value",["macro",21]],["map","fieldName","campaignContent","value",["macro",22]],["map","fieldName","campaignName","value",["macro",23]],["map","fieldName","campaignKeyword","value",["macro",24]],["map","fieldName","alwaysSendReferrer","value","true"],["map","fieldName","legacyHistoryImport","value","false"]],
      "vtp_useHashAutoLink":false,
      "vtp_decorateFormsAutoLink":false,
      "vtp_enableLinkId":false,
      "vtp_dimension":["list",["map","index","1","dimension",["macro",25]],["map","index","2","dimension",["macro",26]],["map","index","3","dimension",["macro",27]],["map","index","6","dimension",["macro",19]],["map","index","8","dimension",["macro",29]],["map","index","29","dimension",["macro",30]],["map","index","30","dimension",["macro",31]],["map","index","4","dimension",["macro",3]],["map","index","5","dimension",["macro",32]],["map","index","34","dimension",["macro",33]]],
      "vtp_enableEcommerce":false,
      "vtp_trackingId":["macro",34],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":false,
      "vtp_enableUseInternalVersion":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventAction"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"eventLabel"
    },{
      "function":"__aev",
      "vtp_setDefaultValue":false,
      "vtp_stripWww":false,
      "vtp_varType":"URL",
      "vtp_component":"HOST"
    },{
      "function":"__aev",
      "vtp_setDefaultValue":false,
      "vtp_varType":"URL",
      "vtp_component":"PATH",
      "vtp_defaultPages":["list"]
    },{
      "function":"__c",
      "vtp_value":["template",["macro",38],["macro",39]]
    },{
      "function":"__v",
      "vtp_name":"gtm.triggers",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":""
    },{
      "function":"__u",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_name":"gtm.scrollThreshold",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.videoStatus",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.videoPercent",
      "vtp_dataLayerVersion":1
    },{
      "function":"__smm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",44],
      "vtp_defaultValue":["macro",44],
      "vtp_map":["list",["map","key","progress","value",["template","progress: ",["macro",45],"%"]]]
    },{
      "function":"__v",
      "vtp_name":"gtm.videoTitle",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementUrl",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"resName"
    },{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_name":"gtm.element",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementClasses",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.elementId",
      "vtp_dataLayerVersion":1
    },{
      "function":"__aev",
      "vtp_varType":"TEXT"
    },{
      "function":"__v",
      "vtp_name":"gtm.scrollUnits",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.scrollDirection",
      "vtp_dataLayerVersion":1
    }],
  "tags":[{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":["template",["macro",3],": ",["macro",4]],
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",35],
      "vtp_eventAction":["macro",36],
      "vtp_eventLabel":["macro",37],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":1
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":["template",["macro",3],": ",["macro",4]],
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",35],
      "vtp_eventAction":["macro",40],
      "vtp_eventLabel":"off domain link",
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":2
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"TRACK_PAGEVIEW",
      "vtp_gaSettings":["macro",35],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "tag_id":3
    },{
      "function":"__sp",
      "once_per_event":true,
      "vtp_conversionId":"949204775",
      "vtp_customParamsFormat":"NONE",
      "vtp_conversionLabel":"zm2nCJ_ghIMBEKfuzsQD",
      "vtp_enableOgtRmktParams":true,
      "vtp_url":["macro",42],
      "tag_id":4
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":true,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":["macro",29],
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",35],
      "vtp_eventAction":"scroll depth",
      "vtp_eventLabel":["template","scroll ",["macro",43],"%"],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":5
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_nonInteraction":false,
      "vtp_overrideGaSettings":false,
      "vtp_eventCategory":["template",["macro",3],": video"],
      "vtp_trackType":"TRACK_EVENT",
      "vtp_gaSettings":["macro",35],
      "vtp_eventAction":["macro",46],
      "vtp_eventLabel":["template","video: ",["macro",47]],
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsEvent":true,
      "tag_id":6
    },{
      "function":"__ua",
      "once_per_event":true,
      "vtp_overrideGaSettings":false,
      "vtp_trackType":"DECORATE_LINK",
      "vtp_gaSettings":["macro",35],
      "vtp_useHashDecorateLink":false,
      "vtp_enableRecaptchaOption":false,
      "vtp_enableUaRlsa":true,
      "vtp_enableUseInternalVersion":false,
      "vtp_enableFirebaseCampaignData":true,
      "vtp_trackTypeIsDecorateLink":true,
      "tag_id":7
    },{
      "function":"__sp",
      "once_per_event":true,
      "vtp_conversionId":"977540931",
      "vtp_customParamsFormat":"NONE",
      "vtp_enableOgtRmktParams":true,
      "vtp_url":["macro",42],
      "tag_id":8
    },{
      "function":"__awct",
      "once_per_event":true,
      "vtp_enableConversionLinker":true,
      "vtp_conversionCookiePrefix":"_gcl",
      "vtp_conversionId":"977540931",
      "vtp_conversionLabel":"q4DjCMLRhpIBEMOukNID",
      "vtp_url":["macro",42],
      "vtp_enableProductReportingCheckbox":false,
      "tag_id":9
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"9326321_12",
      "tag_id":10
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"9326321_13",
      "tag_id":11
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"9326321_14",
      "tag_id":12
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_checkValidation":false,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"9326321_15",
      "tag_id":13
    },{
      "function":"__sdl",
      "vtp_verticalThresholdUnits":"PERCENT",
      "vtp_verticalThresholdsPercent":"0,50,75,100",
      "vtp_verticalThresholdOn":true,
      "vtp_horizontalThresholdOn":false,
      "vtp_uniqueTriggerId":"9326321_16",
      "vtp_enableTriggerStartOption":true,
      "tag_id":14
    },{
      "function":"__ytl",
      "vtp_progressThresholdsPercent":"25,50,75,100",
      "vtp_captureComplete":true,
      "vtp_captureStart":true,
      "vtp_fixMissingApi":true,
      "vtp_radioButtonGroup1":"PERCENTAGE",
      "vtp_capturePause":true,
      "vtp_captureProgress":true,
      "vtp_uniqueTriggerId":"9326321_18",
      "vtp_enableTriggerStartOption":true,
      "tag_id":15
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"trackEvent"
    },{
      "function":"_re",
      "arg0":["macro",40],
      "arg1":"admanager\\.google\\.com\\\/home|\\-dot\\-admanager\\-dot\\-bracket\\-marketing\\-platform\\.appspot\\.com",
      "ignore_case":true
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.linkClick"
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_14($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",40],
      "arg1":"marketingplatform\\.google\\.com\\\/about|\\-dot\\-marketingplatform\\-dot\\-bracket\\-marketing\\-platform\\.appspot\\.com",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_15($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    },{
      "function":"_re",
      "arg0":["macro",14],
      "arg1":"gmp|staging",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"staging\\-dot\\-marketingplatform\\-dot\\-bracket\\-marketing\\-platform\\.appspot\\.com\\\/about|marketingplatform\\.google\\.com",
      "ignore_case":true
    },{
      "function":"_cn",
      "arg0":["macro",8],
      "arg1":"\/about\/partners"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.scrollDepth"
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_16($|,)))"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.video"
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_18($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",48],
      "arg1":"marketingplatform\\.google\\.com|www\\.google\\.com\\\/ads\\\/revenue|blog\\.google\\\/products\\\/admanager",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_12($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",48],
      "arg1":"admanager\\.google\\.com|www\\.google\\.com\\\/ads\\\/revenue|blog\\.google\\\/products\\\/marketingplatform",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^$|((^|,)9326321_13($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",14],
      "arg1":"gam|staging",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"published\\-dot\\-bracket\\-admanager\\-staging\\.proxy\\.preview\\.kintaro\\.goog\\\/home|admanager\\.google\\.com\\\/home",
      "ignore_case":true
    },{
      "function":"_eq",
      "arg0":["macro",14],
      "arg1":"staging"
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"\\\/contact\\-us\\\/thank-you",
      "ignore_case":true
    },{
      "function":"_eq",
      "arg0":["macro",14],
      "arg1":"gam"
    },{
      "function":"_cn",
      "arg0":["macro",14],
      "arg1":"gmp"
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"admanager\\.google\\.com|\\-dot\\-admanager\\-dot\\-bracket\\-marketing\\-platform\\.appspot\\.com",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"marketingplatform\\.google\\.com\\\/about|\\-dot\\-marketingplatform\\-dot\\-bracket\\-marketing\\-platform\\.appspot\\.com",
      "ignore_case":true
    }],
  "rules":[
    [["if",0],["add",0]],
    [["if",2,3],["unless",1],["add",1]],
    [["if",2,5],["unless",4],["add",1]],
    [["if",6],["add",2,13,14]],
    [["if",6,7,8],["unless",9],["add",3]],
    [["if",10,11],["add",4]],
    [["if",12,13],["add",5]],
    [["if",2,14,15],["add",6]],
    [["if",2,16,17],["add",6]],
    [["if",6,18,19],["add",7]],
    [["if",6,18,21],["add",8]],
    [["if",6,22],["add",9]],
    [["if",6,23],["add",10]],
    [["if",6,24],["add",11]],
    [["if",6,25],["add",12]],
    [["if",6],["unless",20],["block",7,8]]]
}