data = {
"resource": {
  "version":"65",
  
  "macros":[{
      "function":"__e"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_type"
    },{
      "function":"__u",
      "vtp_component":"HOST",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__u",
      "vtp_component":"URL",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_channel"
    },{
      "function":"__j",
      "vtp_name":"window.location.hash"
    },{
      "function":"__j",
      "vtp_name":"document.title"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_name"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"page_date"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_subChannel"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_group"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"site_environment"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"prod\"===",["escape",["macro",11],8,16],"?\"UA-6463074-29\":\"UA-6463074-45\"})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return{trackingId:\"",["escape",["macro",12],7],"\",cookieDomain:\"auto\",anonymizeIp:!0,transport:\"beacon\",dataSource:\"web\"}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"interaction_label"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"interaction_category"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"interaction_action"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"ivw_cp"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ivw_context"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ad_type"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"ad_partner"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"ad_placement"
    },{
      "function":"__v",
      "vtp_name":"gtm.elementUrl",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_name":"gtm.triggers",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":""
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var b=",["escape",["macro",22],8,16],",a=document.createElement(\"a\");a.href=b;return a.hostname})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",22],8,16],";if(-1\u003Ca.indexOf(\"taboola\")){var b=document.createElement(\"a\");b.href=a;return b.hostname}return a})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"eventCategory"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"eventAction"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"eventLabel"
    },{
      "function":"__v",
      "vtp_name":"gtm.scrollThreshold",
      "vtp_dataLayerVersion":1
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"social_network"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"social_action"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"social_target"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"lieferant"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"sportart"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"liga"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"sendung"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"category"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"keywords"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"other",
      "vtp_name":"page_seo_type"
    },{
      "function":"__v",
      "convert_true_to":"yes",
      "convert_false_to":"no",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"undefined",
      "vtp_name":"page_withvideo"
    },{
      "function":"__u",
      "vtp_component":"PATH",
      "vtp_enableMultiQueryKeys":false,
      "vtp_enableIgnoreEmptyQueryParam":false
    },{
      "function":"__j",
      "convert_undefined_to":"false",
      "vtp_name":"windowLoaded"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_content_id"
    },{
      "function":"__dbg"
    },{
      "function":"__jsm",
      "convert_undefined_to":"604261",
      "vtp_javascript":["template","(function(){if(!0===",["escape",["macro",44],8,16],")return\"604261\";try{var a=document.location.hostname,b=\"\";return b=0===a.indexOf(\"www.sport1.de\")||0===a.indexOf(\"m.sport1.de\")?\"604311\":\"604261\"}catch(c){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=document.location.hostname,b=\"\";return b=0===a.indexOf(\"m.\")?\"mobile_web\":\"desktop\"}catch(c){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=document.location.hostname,b=\"\";return b=0===a.indexOf(\"m.\")?\"mobile_web\":\"desktop\"}catch(c){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=document.title||\"\";return a.toLowerCase()})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=[\"\/",["escape",["macro",17],7],"\".replace(\/_\/ig,\"\/\"),\"",["escape",["macro",18],7],"\"];a=a.join(\"\/\").replace(\/[\\\/]*$\/i,\"\");return a.toLowerCase()}catch(b){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=",["escape",["macro",8],8,16],",b=\"\";void 0!==a\u0026\u0026(b=a.split(\"T\")[0]);return b}catch(c){}})();"]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=",["escape",["macro",8],8,16],",b=\"\";if(void 0!==a){var d=a.split(\"T\")[1].split(\"+\")[0],c=d.split(\":\");c.pop();b=c.join(\":\")}return b}catch(e){}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_adLevel1"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_adLevel2"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_adLevel3"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"page_article_type"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){try{var a=document.location.hostname,b=\"\";return b=0===a.indexOf(\"m.\")?\"2\":\"1\"}catch(c){}})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"video_play"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"video_id"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"date"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"video_adLevel1"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"video_adLevel2"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"video_adLevel2"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return function(a){window.atiTag.click.send(a)}})();"]
    },{
      "function":"__j",
      "vtp_name":"impressionList"
    },{
      "function":"__j",
      "vtp_name":"openClickHits"
    },{
      "function":"__j",
      "convert_undefined_to":"false",
      "vtp_name":"sendSingleImpressions"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return function(a){window.atiTag.publisher.send({impression:a})}})();"]
    },{
      "function":"__j",
      "convert_undefined_to":"false",
      "vtp_name":"firstImpressionLoaded"
    },{
      "function":"__e"
    },{
      "function":"__r"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",70],8,16],"%100;return 101\u003Ea?!0:!1})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"site_platform"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"site_deviceCategory"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"site_domain"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"site_language"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":true,
      "vtp_defaultValue":"",
      "vtp_name":"ivw_co"
    },{
      "function":"__smm",
      "vtp_setDefaultValue":true,
      "vtp_input":["macro",72],
      "vtp_defaultValue":"sport1-ivw-error",
      "vtp_map":["list",["map","key","web","value","sport1"],["map","key","mobile","value","mobsport1"]]
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"",["escape",["macro",1],7],",",["escape",["macro",4],7],"\"})();"]
    },{
      "function":"__c",
      "vtp_value":"sport1.de"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"interaction_type"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",3],8,16],";return a.replace(\/(newslettermail=)([a-zA-Z0-9.!#$%\u0026'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*)(.*)\/,\"$1email$3\").replace(\/(email=)([a-zA-Z0-9.!#$%\u0026'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*)(.*)\/,\"$1email$3\")})();"]
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"eventNonInteraction"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"eventValue"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"optimizely-dimension-number"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"optimizely-dimension-value"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_setDefaultValue":false,
      "vtp_name":"optimizely-referrer"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"socialAction"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"socialNetwork"
    },{
      "function":"__v",
      "vtp_dataLayerVersion":2,
      "vtp_name":"socialTarget"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){var a=",["escape",["macro",3],8,16],";return a.replace(\/https?:\\\/\\\/[^\\\/]+\/i,\"\")})();"]
    },{
      "function":"__j",
      "vtp_name":"dataLayer"
    },{
      "function":"__jsm",
      "vtp_javascript":["template","(function(){return\"\"})();"]
    },{
      "function":"__f",
      "vtp_component":"URL"
    }],
  "tags":[{
      "function":"__html",
      "priority":10,
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._gtm.ga.addCustom({metric1:\"1\"});\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":31
    },{
      "function":"__html",
      "priority":10,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.addCustom({dimension13:\"",["escape",["macro",33],7],"\",dimension14:\"",["escape",["macro",34],7],"\",dimension15:\"",["escape",["macro",35],7],"\",dimension16:\"",["escape",["macro",36],7],"\",dimension17:\"",["escape",["macro",37],7],"\",dimension18:\"",["escape",["macro",38],7],"\"})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":34
    },{
      "function":"__html",
      "priority":10,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._gtm=window._gtm||{};\nwindow._gtm.ga=function(q,r,l,m){if(window._gtm.initLogic)return window._gtm.ga;window._gtm.initLogic=!0;var d=[],c=[],e=0,f=0,n=null,p=!0===m||\"true\"===m?0:1,h=function(){var a=0\u003Carguments.length\u0026\u0026void 0!==arguments[0]?arguments[0]:\"forcetracking\";d.length\u003Ee\u0026\u0026c.length===f\u0026\u00260!==f\u0026\u0026c.push([\"send\",{hitType:\"event\",eventCategory:\"technical\",eventAction:a,eventLabel:\"\",nonInteraction:!0}]);g()},g=function(){if(c.length-p\u003Ef){for(var a=d.length;e\u003Ca;e++)l.apply(this,d[e]);e=a;l.apply(this,c[f]);f=c.length-\np}},k=function(a,b){a[1]?(a[1]!==n\u0026\u0026h(\"changedaction\"),n=a[1],d.push(b),d.push(a)):d.push(b);12\u003Cd.length-e\u0026\u0026h(\"queue_full\")};return{addProduct:function(a,b){k([\"ec:setAction\",a],[\"ec:addProduct\",b])},addPromotion:function(){k([\"ec:setAction\",0\u003Carguments.length\u0026\u0026void 0!==arguments[0]?arguments[0]:void 0],[\"ec:addPromo\",arguments[1]])},addCustom:function(){k([void 0,void 0],[\"set\",0\u003Carguments.length\u0026\u0026void 0!==arguments[0]?arguments[0]:{}])},trackEvent:function(a,b){c.push([\"send\",{hitType:\"event\",eventCategory:a,\neventAction:b,eventLabel:2\u003Carguments.length\u0026\u0026void 0!==arguments[2]?arguments[2]:\"\",nonInteraction:3\u003Carguments.length\u0026\u0026void 0!==arguments[3]?arguments[3]:!0}]);g()},trackSocial:function(a,b){c.push([\"send\",{hitType:\"social\",socialNetwork:a,socialAction:b,socialTarget:2\u003Carguments.length\u0026\u0026void 0!==arguments[2]?arguments[2]:\"\"}]);g()},trackPageview:function(a,b){c.push([\"send\",{hitType:\"pageview\",location:a,title:b}]);g()},forceTrack:function(){h()},getBuffer:function(){return c},getQueue:function(){return d}}}(window,\ndocument,function(){window.ga.apply(this,arguments)},",["escape",["macro",71],8,16],");\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":1
    },{
      "function":"__html",
      "priority":5,
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow.sendSingleImpressions=!1;window.firstImpressionLoaded=!1;window.impressionList=[];if(null!==",["escape",["macro",43],8,16],"\u0026\u0026\"\"!==",["escape",["macro",43],8,16],")var content_id=",["escape",["macro",43],8,16],".toString();\ntry{var cusObj={globVars:{source:",["escape",["macro",46],8,16],"||\"\",platform:",["escape",["macro",47],8,16],"||\"\",title:",["escape",["macro",48],8,16],"||\"\",clean_url:",["escape",["macro",41],8,16],"||\"\",full_url:",["escape",["macro",3],8,16],"||\"\",ivw_code:",["escape",["macro",49],8,16],"||\"\",virtual_pi:\"yes\",seo_type:",["escape",["macro",39],8,16],"||\"\",page_withvideo:",["escape",["macro",40],8,16],"||\"\",channel:",["escape",["macro",4],8,16],"||\"\",subchannel:",["escape",["macro",9],8,16],"||\"\",page_type:",["escape",["macro",1],8,16],"||\"\",page_group:",["escape",["macro",10],8,16],"||\"\",page_date:",["escape",["macro",50],8,16],"||\n\"\",page_time:",["escape",["macro",51],8,16],"||\"\",page_adLevel1:",["escape",["macro",52],8,16],"||\"\",page_adLevel2:",["escape",["macro",53],8,16],"||\"\",page_adLevel3:",["escape",["macro",54],8,16],"||\"\",page_content_id:content_id||\"\",article_type:",["escape",["macro",55],8,16],"||\"\"}};window.atiTag.page.send({name:",["escape",["macro",41],8,16],",level2:",["escape",["macro",56],8,16],",customObject:cusObj})}catch(a){console.log(\"%c Error in ATI-02a.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":51
    },{
      "function":"__html",
      "priority":1,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"",["escape",["macro",7],7],"\";if(",["escape",["macro",1],8,16],"\u0026\u0026",["escape",["macro",8],8,16],"\u0026\u0026(\"artikel\"===",["escape",["macro",1],8,16],"||\"bildergalerien\"===",["escape",["macro",1],8,16],"||\"video\"===",["escape",["macro",1],8,16],")){var b=",["escape",["macro",8],8,16],";\/^\\d\\d\\d\\d-\\d\\d-\\d\\d\/i.test(b)\u0026\u0026(a=b.slice(0,10)+\"-",["escape",["macro",7],7],"\")}a=[\"",["escape",["macro",4],7],"\",\"",["escape",["macro",9],7],"\",\"",["escape",["macro",1],7],"\",\"",["escape",["macro",10],7],"\",a];a=a.join(\"\/\").replace(\/[\\\/]*$\/i,\"\");window._gtm.ga.addCustom({dimension2:a})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":4
    },{
      "function":"__html",
      "priority":1,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=[\"\/",["escape",["macro",17],7],"\".replace(\/_\/ig,\"\/\"),\"",["escape",["macro",18],7],"\"];a=a.join(\"\/\").replace(\/[\\\/]*$\/i,\"\");window._gtm.ga.addCustom({dimension3:a})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":11
    },{
      "function":"__html",
      "priority":1,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.addCustom({dimension19:\"",["escape",["macro",39],7],"\"})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":35
    },{
      "function":"__html",
      "priority":1,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.addCustom({dimension20:",["escape",["macro",40],8,16],"})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":36
    },{
      "function":"__paused",
      "vtp_originalTagType":"html",
      "tag_id":13
    },{
      "function":"__paused",
      "vtp_originalTagType":"html",
      "tag_id":45
    },{
      "function":"__paused",
      "vtp_originalTagType":"html",
      "tag_id":70
    },{
      "function":"__lcl",
      "vtp_waitForTags":true,
      "vtp_checkValidation":true,
      "vtp_waitForTagsTimeout":"2000",
      "vtp_uniqueTriggerId":"9010567_34",
      "tag_id":71
    },{
      "function":"__sdl",
      "vtp_verticalThresholdUnits":"PERCENT",
      "vtp_verticalThresholdsPercent":"0,25,50,75,95",
      "vtp_verticalThresholdOn":true,
      "vtp_horizontalThresholdOn":false,
      "vtp_uniqueTriggerId":"9010567_41",
      "vtp_enableTriggerStartOption":true,
      "tag_id":72
    },{
      "function":"__html",
      "setup_tags":["list",["tag",2,0]],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.addCustom({contentGroup1:\"",["escape",["macro",4],7],"\",contentGroup2:",["escape",["macro",9],8,16],"?\"",["escape",["macro",9],7],"\":\"undefined\",contentGroup3:\"",["escape",["macro",1],7],"\",contentGroup4:",["escape",["macro",10],8,16],"?\"",["escape",["macro",10],7],"\":\"undefined\"})})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":5
    },{
      "function":"__html",
      "setup_tags":["list",["tag",2,0]],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm=window._gtm||{};window._gtm.initialized||(function(a,e,f,g,b,c,d){a.GoogleAnalyticsObject=b;a[b]=a[b]||function(){(a[b].q=a[b].q||[]).push(arguments)};a[b].l=1*new Date;c=e.createElement(f);d=e.getElementsByTagName(f)[0];c.async=1;c.src=g;d.parentNode.insertBefore(c,d)}(window,document,\"script\",\"https:\/\/www.google-analytics.com\/analytics.js\",\"ga\"),ga(\"create\",",["escape",["macro",13],8,16],"),ga(\"set\",\"anonymizeIp\",!0),ga(\"require\",\"ec\"),window._gtm.initialized=!0)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":6
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){if(",["escape",["macro",19],8,16],"){var a={id:\"",["escape",["macro",20],7],"_",["escape",["macro",21],7],"_",["escape",["macro",19],7],"\",name:\"",["escape",["macro",20],7],"\",creative:\"",["escape",["macro",19],7],"\",position:\"",["escape",["macro",21],7],"\"};window._gtm.ga.addPromotion(null,a)}})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":12
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){if(",["escape",["macro",19],8,16],"){var a=\"ad\",b=\"",["escape",["macro",20],7],"_click\",c=\"",["escape",["macro",19],7],"\"+",["escape",["macro",21],8,16],"?\"_",["escape",["macro",21],7],"\":\"\";window._gtm.ga.trackEvent(a,b,c)}})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":14
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._adftrack=Array.isArray(window._adftrack)?window._adftrack:window._adftrack?[window._adftrack]:[];window._adftrack.push({pm:1160440,divider:encodeURIComponent(\"|\"),pagename:encodeURIComponent(\"Article Page | La - Liga\")});(function(){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"https:\/\/track.adform.net\/serving\/scripts\/trackpoint\/async\/\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();\u003C\/script\u003E\n\n\u003Cnoscript\u003E\n\n    \u003Cp style=\"margin:0;padding:0;border:0;\"\u003E\n\n        \u003Cimg src=\"https:\/\/track.adform.net\/Serving\/TrackPoint\/?pm=1160440\u0026amp;ADFPageName=Article%20Page%20%7C%20La%20-%20Liga\u0026amp;ADFdivider=|\" width=\"1\" height=\"1\" alt=\"\"\u003E\n\n    \u003C\/p\u003E\n\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":15
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._adftrack=Array.isArray(window._adftrack)?window._adftrack:window._adftrack?[window._adftrack]:[];window._adftrack.push({pm:1160440,divider:encodeURIComponent(\"|\"),pagename:encodeURIComponent(\"Int Football Category | La - Liga\")});(function(){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"https:\/\/track.adform.net\/serving\/scripts\/trackpoint\/async\/\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();\u003C\/script\u003E\n\n\u003Cnoscript\u003E\n\n    \u003Cp style=\"margin:0;padding:0;border:0;\"\u003E\n\n        \u003Cimg src=\"https:\/\/track.adform.net\/Serving\/TrackPoint\/?pm=1160440\u0026amp;ADFPageName=Int%20Football%20Category%20%7C%20La%20-%20Liga\u0026amp;ADFdivider=|\" width=\"1\" height=\"1\" alt=\"\"\u003E\n\n    \u003C\/p\u003E\n\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":16
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._adftrack=Array.isArray(window._adftrack)?window._adftrack:window._adftrack?[window._adftrack]:[];window._adftrack.push({pm:1160440,divider:encodeURIComponent(\"|\"),pagename:encodeURIComponent(\"Article Page | NBA\")});(function(){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"https:\/\/track.adform.net\/serving\/scripts\/trackpoint\/async\/\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();\u003C\/script\u003E\n\n\u003Cnoscript\u003E\n\n    \u003Cp style=\"margin:0;padding:0;border:0;\"\u003E\n\n        \u003Cimg src=\"https:\/\/track.adform.net\/Serving\/TrackPoint\/?pm=1160440\u0026amp;ADFPageName=Article%20Page%20%7C%20NBA\u0026amp;ADFdivider=|\" width=\"1\" height=\"1\" alt=\"\"\u003E\n\n    \u003C\/p\u003E\n\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":17
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._adftrack=Array.isArray(window._adftrack)?window._adftrack:window._adftrack?[window._adftrack]:[];window._adftrack.push({pm:1160440,divider:encodeURIComponent(\"|\"),pagename:encodeURIComponent(\"US - Sport Category | NBA\")});(function(){var a=document.createElement(\"script\");a.type=\"text\/javascript\";a.async=!0;a.src=\"https:\/\/track.adform.net\/serving\/scripts\/trackpoint\/async\/\";var b=document.getElementsByTagName(\"script\")[0];b.parentNode.insertBefore(a,b)})();\u003C\/script\u003E\n\n\u003Cnoscript\u003E\n\n    \u003Cp style=\"margin:0;padding:0;border:0;\"\u003E\n\n        \u003Cimg src=\"https:\/\/track.adform.net\/Serving\/TrackPoint\/?pm=1160440\u0026amp;ADFPageName=US%20-%20Sport%20Category%20%7C%20NBA\u0026amp;ADFdivider=|\" width=\"1\" height=\"1\" alt=\"\"\u003E\n\n    \u003C\/p\u003E\n\n\u003C\/noscript\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":18
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"optimizely\",b=\"assigned_to_campaign\",c=\"\";window._gtm.ga.trackEvent(a,b,c)})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":20
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Evar DATALAYER_OBJECT_NAME=\"dataLayer\",referrerOverride=function(c){(window[DATALAYER_OBJECT_NAME]||[]).push({event:\"optimizely-referrer-override\",\"optimizely-referrer\":c})},sendCampaignData=function(c,d,g,e,b,a,f,k,h){if(e=optimizely.get(\"data\")\u0026\u0026optimizely.get(\"data\").campaigns[d]\u0026\u0026optimizely.get(\"data\").campaigns[d].integrationSettings\u0026\u0026optimizely.get(\"data\").campaigns[d].integrationSettings.google_universal_analytics\u0026\u0026optimizely.get(\"data\").campaigns[d].integrationSettings.google_universal_analytics.universal_analytics_slot)c=\nc?c+\"(\"+d+\")\":d,g=g.join(\",\"),b=[c,b?b+\"(\"+a+\")\":g+\"(\"+a+\")\",f?f+\"(\"+k+\")\":k,h?\"holdback\":\"treatment\"].join(\":\"),(window[DATALAYER_OBJECT_NAME]||[]).push({event:\"campaign-decided\",\"optimizely-dimension-value\":b,\"optimizely-dimension-number\":e})},initNewOptimizelyIntegration=function(c,d){var g=!1,e=function(b){var a=window.optimizely.get\u0026\u0026window.optimizely.get(\"state\"),f=a.getRedirectInfo()\u0026\u0026a.getRedirectInfo().referrer;!g\u0026\u0026f\u0026\u0026(c(f),g=!0);a=a.getCampaignStates({isActive:!0})[b];f=a.campaignName;if(0\u003C\na.audiences.length)var e=a.audiences.map(function(a){return a.name}),h=a.audiences.map(function(a){return a.id});else e=[\"everyone_else\"],h=[0];d(f,b,e,h,a.experiment.name,a.experiment.id,a.variation.name,a.variation.id,a.isInCampaignHoldback)};(function(){var b=window.optimizely.get\u0026\u0026window.optimizely.get(\"state\");if(b){b=b.getCampaignStates({isActive:!0});for(var a in b)e(a)}})();(function(){window.optimizely=window.optimizely||[];window.optimizely.push({type:\"addListener\",filter:{type:\"lifecycle\",\nname:\"campaignDecided\"},handler:function(b){e(b.data.campaign.id)}})})()},initOptimizelyIntegration=function(c,d){initNewOptimizelyIntegration(c,d)};initOptimizelyIntegration(referrerOverride,sendCampaignData);\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":21
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"optimizely\",b=\"referrer_override\",c=\"\";window._gtm.ga.trackEvent(a,b,c)})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":22
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"outbound-link\",b=\"",["escape",["macro",24],7],"\",c=\"",["escape",["macro",25],7],"\";window._gtm.ga.trackEvent(a,b,c)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":23
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"",["escape",["macro",26],7],"\",b=\"",["escape",["macro",27],7],"\",c=\"",["escape",["macro",28],7],"\";window._gtm.ga.trackEvent(a,b,c)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":24
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"",["escape",["macro",26],7],"\",b=\"",["escape",["macro",27],7],"\",c=\"",["escape",["macro",28],7],"\";window._gtm.ga.trackEvent(a,b,c,!1)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":25
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._gtm\u0026\u0026(window._gtm.scroll=",["escape",["macro",29],8,16],");\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":27
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.addCustom({dimension4:window.location.href})})();\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":28
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var a=\"",["escape",["macro",30],7],"\",b=\"",["escape",["macro",31],7],"\",c=",["escape",["macro",32],8,16],"?\"",["escape",["macro",32],7],"\":\"\";window._gtm.ga.trackSocial(a,b,c)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":29
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){if(",["escape",["macro",19],8,16],"){var a={id:\"",["escape",["macro",20],7],"_",["escape",["macro",21],7],"_",["escape",["macro",19],7],"\",name:\"",["escape",["macro",20],7],"\",creative:\"",["escape",["macro",19],7],"\",position:\"",["escape",["macro",21],7],"\"};window._gtm.ga.addPromotion(\"promo_click\",a)}})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":30
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Eif(\"www.sport1.de\"===",["escape",["macro",2],8,16],")var script_url=\"\/\/c2.taboola.com\/nr\/sport1de-sport1-desktop0\/newsroom.js\";else\"m.sport1.de\"===",["escape",["macro",2],8,16],"\u0026\u0026(script_url=\"\/\/c2.taboola.com\/nr\/sport1de-sport1\/newsroom.js\");\nscript_url\u0026\u0026(window._newsroom=window._newsroom||[],window._newsroom.push({pageTemplate:\"home\"}),window._newsroom.push({pageDashboard:\"home\"}),window._newsroom.push(\"auditClicks\"),window._newsroom.push(\"trackPage\"),!function(a,b,c){a.async=1;a.src=c;b.parentNode.insertBefore(a,b)}(document.createElement(\"script\"),document.getElementsByTagName(\"script\")[0],script_url));\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":47
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Eif(\"www.sport1.de\"===",["escape",["macro",2],8,16],")var script_url=\"\/\/c2.taboola.com\/nr\/sport1de-sport1-desktop0\/newsroom.js\";else\"m.sport1.de\"===",["escape",["macro",2],8,16],"\u0026\u0026(script_url=\"\/\/c2.taboola.com\/nr\/sport1de-sport1\/newsroom.js\");script_url\u0026\u0026(window._newsroom=window._newsroom||[],!function(a,b,c){a.async=1;a.src=c;b.parentNode.insertBefore(a,b)}(document.createElement(\"script\"),document.getElementsByTagName(\"script\")[0],script_url));\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":48
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Evar script_url=\"\/\/inhabit-service.cdn.arkadiumhosted.com\/Widget\/v1\/\";!function(a,b,c){a.async=1;a.src=c;a.setAttribute(\"data-ark-client\",\"36d38ce9-255e-4e07-8659-5ccf0eeda0d2\");b.parentNode.insertBefore(a,b)}(document.createElement(\"script\"),document.getElementsByTagName(\"script\")[0],script_url);\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":49
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{var cdn=\"\/\/tag.aticdn.net\/604311\/smarttag.js\",scr=document.createElement(\"script\");if(null!==",["escape",["macro",43],8,16],"\u0026\u0026\"\"!==",["escape",["macro",43],8,16],")var content_id=",["escape",["macro",43],8,16],".toString();scr.src=cdn;scr.onload=function(){window.atiTag=new ATInternet.Tracker.Tag({site:",["escape",["macro",45],8,16],"});dataLayer.push({event:\"atiTagInit\"});var a={globVars:{source:",["escape",["macro",46],8,16],"||\"\",platform:",["escape",["macro",47],8,16],"||\"\",title:",["escape",["macro",48],8,16],"||\"\",clean_url:",["escape",["macro",41],8,16],"||\"\",full_url:",["escape",["macro",3],8,16],"||\n\"\",ivw_code:",["escape",["macro",49],8,16],"||\"\",virtual_pi:\"no\",seo_type:",["escape",["macro",39],8,16],"||\"\",page_withvideo:",["escape",["macro",40],8,16],"||\"\",channel:",["escape",["macro",4],8,16],"||\"\",subchannel:",["escape",["macro",9],8,16],"||\"\",page_type:",["escape",["macro",1],8,16],"||\"\",page_group:",["escape",["macro",10],8,16],"||\"\",page_date:",["escape",["macro",50],8,16],"||\"\",page_time:",["escape",["macro",51],8,16],"||\"\",page_adLevel1:",["escape",["macro",52],8,16],"||\"\",page_adLevel2:",["escape",["macro",53],8,16],"||\"\",page_adLevel3:",["escape",["macro",54],8,16],"||\"\",page_content_id:content_id||\n\"\",article_type:",["escape",["macro",55],8,16],"||\"\"}};window.atiTag.page.set({name:",["escape",["macro",41],8,16],",level2:",["escape",["macro",56],8,16],",customObject:a});window.atiTag.dispatch()};document.head.appendChild(scr)}catch(a){console.log(\"%c Error in ATI-01.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":50
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{var chp1=",["escape",["macro",15],8,16],"||\"\",chp2=",["escape",["macro",16],8,16],"||\"\",chp3=",["escape",["macro",14],8,16],"||\"\",lvl2=",["escape",["macro",56],8,16],"||\"\",nm=\"click\",tp=\"action\",cusObj={globVars:{source:",["escape",["macro",46],8,16],"||\"\",platform:",["escape",["macro",47],8,16],"||\"\",title:",["escape",["macro",48],8,16],"||\"\",clean_url:",["escape",["macro",41],8,16],"||\"\",full_url:",["escape",["macro",3],8,16],"||\"\"}};\"video\"===",["escape",["macro",15],8,16],".toLowerCase()\u0026\u0026(cusObj.globVars.video_keywords=",["escape",["macro",38],8,16],"||\"\",cusObj.globVars.video_category=",["escape",["macro",37],8,16],"||\n\"\",cusObj.globVars.video_lieferant=",["escape",["macro",33],8,16],"||\"\",cusObj.globVars.video_liga=",["escape",["macro",35],8,16],"||\"\",cusObj.globVars.video_sendung=",["escape",["macro",36],8,16],"||\"\",cusObj.globVars.video_sportart=",["escape",["macro",34],8,16],"||\"\",cusObj.globVars.video_playback=",["escape",["macro",57],8,16],"||\"\",cusObj.globVars.page_content_id=",["escape",["macro",58],8,16],"||\"\",cusObj.globVars.page_date=",["escape",["macro",59],8,16],"||\"\",cusObj.globVars.page_adLevel1=",["escape",["macro",60],8,16],"||\"\",cusObj.globVars.page_adLevel2=",["escape",["macro",61],8,16],"||\n\"\",cusObj.globVars.page_adLevel3=",["escape",["macro",62],8,16],"||\"\");var clickObject={chapter1:encodeURIComponent(chp1.toLowerCase()),chapter2:encodeURIComponent(chp2.toLowerCase()),chapter3:encodeURIComponent(chp3),name:nm,level2:lvl2,type:tp,customObject:cusObj};if(window.atiTag)",["escape",["macro",63],8,16],"(clickObject);else{if(\"undefined\"===typeof openClickHits)var openClickHits=[];openClickHits.push({chapter1:encodeURIComponent(chp1.toLowerCase()),chapter2:encodeURIComponent(chp2.toLowerCase()),chapter3:encodeURIComponent(chp3),\nname:nm,level2:lvl2,type:tp,customObject:cusObj})}}catch(a){console.log(\"%c Error in ATI-03.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":52
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{var chp1=",["escape",["macro",31],8,16],"||\"\",chp2=",["escape",["macro",30],8,16],"||\"\",chp3=",["escape",["macro",32],8,16],"||\"\",lvl2=",["escape",["macro",56],8,16],"||\"\",nm=\"social_click\",tp=\"action\",cusObj={globVars:{source:",["escape",["macro",46],8,16],"||\"\",platform:",["escape",["macro",47],8,16],"||\"\",title:",["escape",["macro",48],8,16],"||\"\",clean_url:",["escape",["macro",41],8,16],"||\"\",full_url:",["escape",["macro",3],8,16],"||\"\"}},clickObject={chapter1:encodeURIComponent(chp1.toLowerCase()),chapter2:encodeURIComponent(chp2.toLowerCase()),chapter3:encodeURIComponent(chp3.toLowerCase()),\nname:nm,level2:lvl2,type:tp,customObject:cusObj};",["escape",["macro",63],8,16],"(clickObject)}catch(a){console.log(\"%c Error in ATI-04.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":53
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Eif(void 0!==",["escape",["macro",64],8,16],"){for(var i=0;i\u003C",["escape",["macro",64],8,16],".length;i++)window.atiTag.publisher.add({impression:",["escape",["macro",64],8,16],"[i]});1\u003C=",["escape",["macro",64],8,16],".length\u0026\u0026window.atiTag.dispatch()}window.windowLoaded=!0;window.sendSingleImpressions=!0;\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":54
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{if(0\u003C",["escape",["macro",65],8,16],".length)for(var i=0;i\u003C",["escape",["macro",65],8,16],".length;i++)",["escape",["macro",63],8,16],"(",["escape",["macro",65],8,16],"[i])}catch(a){};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":56
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{var _cmpId=",["escape",["macro",20],8,16],"||\"\",_crtn=",["escape",["macro",19],8,16],"||\"\",_vrnt=",["escape",["macro",21],8,16],"||\"\",_frmt=[_cmpId,_crtn,_vrnt].filter(Boolean).join(\"_\");window.atiTag.publisher.send({click:{campaignId:\"[\"+encodeURIComponent(_cmpId.toLowerCase())+\"]\",creation:\"[\"+encodeURIComponent(_crtn.toLowerCase())+\"]\",variant:\"[\"+encodeURIComponent(_vrnt.toLowerCase())+\"]\",format:\"[\"+encodeURIComponent(_frmt.toLowerCase())+\"]\"}})}catch(a){console.log(\"%c Error in ATI-06.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":57
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Etry{var _cmpId=",["escape",["macro",20],8,16],"||\"\",_crtn=",["escape",["macro",19],8,16],"||\"\",_vrnt=",["escape",["macro",21],8,16],"||\"\",_frmt=[_cmpId,_crtn,_vrnt].filter(Boolean).join(\"_\"),_impressionObject={campaignId:\"[\"+encodeURIComponent(_cmpId.toLowerCase())+\"]\",creation:\"[\"+encodeURIComponent(_crtn.toLowerCase())+\"]\",variant:\"[\"+encodeURIComponent(_vrnt.toLowerCase())+\"]\",format:\"[\"+encodeURIComponent(_frmt.toLowerCase())+\"]\"};",["escape",["macro",67],8,16],"(_impressionObject)}catch(a){console.log(\"%c Error in ATI-05b.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":62
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Ewindow.firstImpressionLoaded||(window.firstImpressionLoaded=!0,setTimeout(function(){if(void 0!==",["escape",["macro",64],8,16],"){for(var a=0;a\u003C",["escape",["macro",64],8,16],".length;a++)window.atiTag.publisher.add({impression:",["escape",["macro",64],8,16],"[a]});1\u003C=",["escape",["macro",64],8,16],".length\u0026\u0026window.atiTag.dispatch()}},2E3));\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":64
    },{
      "function":"__html",
      "metadata":["map"],
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003Eif(null!==",["escape",["macro",43],8,16],"\u0026\u0026\"\"!==",["escape",["macro",43],8,16],")var content_id=",["escape",["macro",43],8,16],".toString();\ntry{var cusObj={globVars:{source:",["escape",["macro",46],8,16],"||\"\",platform:",["escape",["macro",47],8,16],"||\"\",title:",["escape",["macro",48],8,16],"||\"\",clean_url:",["escape",["macro",41],8,16],"||\"\",full_url:",["escape",["macro",3],8,16],"||\"\",ivw_code:",["escape",["macro",49],8,16],"||\"\",virtual_pi:\"yes\",seo_type:",["escape",["macro",39],8,16],"||\"\",page_withvideo:",["escape",["macro",40],8,16],"||\"\",channel:",["escape",["macro",4],8,16],"||\"\",subchannel:",["escape",["macro",9],8,16],"||\"\",page_type:",["escape",["macro",1],8,16],"||\"\",page_group:",["escape",["macro",10],8,16],"||\"\",page_date:",["escape",["macro",50],8,16],"||\n\"\",page_time:",["escape",["macro",51],8,16],"||\"\",page_adLevel1:",["escape",["macro",52],8,16],"||\"\",page_adLevel2:",["escape",["macro",53],8,16],"||\"\",page_adLevel3:",["escape",["macro",54],8,16],"||\"\",page_content_id:content_id||\"\",article_type:",["escape",["macro",55],8,16],"||\"\"}};window.atiTag.page.send({name:",["escape",["macro",41],8,16],",level2:",["escape",["macro",56],8,16],",customObject:cusObj})}catch(a){console.log(\"%c Error in ATI-02b.\",\"font-weight: bold; color: red;\")};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":65
    },{
      "function":"__html",
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E\"undefined\"===typeof window.impressionList\u0026\u0026(window.impressionList=[]);\nif(\"ad.impression\"===",["escape",["macro",69],8,16],"){var _cmpId=",["escape",["macro",20],8,16],"||\"\",_crtn=",["escape",["macro",19],8,16],"||\"\",_vrnt=",["escape",["macro",21],8,16],"||\"\",_frmt=[_cmpId,_crtn,_vrnt].filter(Boolean).join(\"_\"),impressionObject={campaignId:\"[\"+encodeURIComponent(_cmpId.toLowerCase())+\"]\",creation:\"[\"+encodeURIComponent(_crtn.toLowerCase())+\"]\",variant:\"[\"+encodeURIComponent(_vrnt.toLowerCase())+\"]\",format:\"[\"+encodeURIComponent(_frmt.toLowerCase())+\"]\"};window.impressionList.push(impressionObject)};\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":66
    },{
      "function":"__html",
      "priority":-10,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var b=\"",["escape",["macro",3],7],"\";if(\"suche\"==",["escape",["macro",4],8,16],"){var a=document.createElement(\"a\");a.href=b+",["escape",["macro",5],8,16],";b=a.protocol+a.hostname+a.pathname+(a.search?a.search+\"\\x26srch\\x3d\":\"?srch\\x3d\")+a.hash.substring(1)}window._gtm.ga.trackPageview(b,\"",["escape",["macro",6],7],"\")})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":3
    },{
      "function":"__html",
      "priority":-10,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){var vid=\"",["escape",["macro",15],7],"\".toLowerCase().indexOf(\"video\")\u003E-1?false:true;window._gtm.ga.trackEvent(\"",["escape",["macro",15],7],"\".toLowerCase(),\"",["escape",["macro",16],7],"\".toLowerCase(),\"",["escape",["macro",14],7],"\".toLowerCase(),vid)})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":9
    },{
      "function":"__html",
      "priority":-10,
      "once_per_event":true,
      "vtp_html":["template","\u003Cscript type=\"text\/gtmscript\"\u003E(function(){window._gtm.ga.trackPageview(\"",["escape",["macro",3],7],"\",\"",["escape",["macro",6],7],"\")})();\u003C\/script\u003E"],
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":10
    },{
      "function":"__html",
      "priority":-50,
      "once_per_event":true,
      "vtp_html":"\u003Cscript type=\"text\/gtmscript\"\u003Ewindow._gtm=window._gtm||{};\nwindow._gtm.unload=function(g){var b={},d=function(a,c,f){a.addEventListener?a.addEventListener(c,f,!1):a.attachEvent\u0026\u0026a.attachEvent(\"on\"+c,f);b[c]=b[c]||[];b[c].push({el:a,fn:f})};return{waitABit:function(){for(var b=(new Date).getTime();50\u003E(new Date).getTime()-b;);},add:function(a,c,f){var k=function(a,c){f\u0026\u0026!g._wedidit\u0026\u0026(f.call(this,a||g.event,c),g._wedidit=!0);for(var h in b)if(b.hasOwnProperty(h))for(;b[h].length;){c=b[h][0].el;var e=h,d=b[h][0].fn;c.removeEventListener?c.removeEventListener(e,\nd,!1):c.detachEvent\u0026\u0026c.detachEvent(\"on\"+e,d);if(b.hasOwnProperty(e))for(a=0;a\u003Cb[e].length;a++)if(d===b[e][a].fn\u0026\u0026c===b[e][a].el){b[e].splice(a,1);break}}b={}},l=function(a){\"hidden\"===document.visibilityState\u0026\u0026k(a,\"visibility\")};\"unload\"===c\u0026\u0026(document.visibilityState\u0026\u0026\/iphone|ipod|android|blackberry|fennec\/.test(navigator.userAgent.toLowerCase())\u0026\u0026d(document,\"visibilitychange\",l),g.onpagehide||null===g.onpagehide?d(a,\"pagehide\",k):d(a,\"unload\",k));d(a,\"beforeunload\",k)}}}(window);\nwindow._gtm.unload.add(window,\"unload\",function(){window._gtm.ga.trackEvent(\"scrollability\",\"scroll_\"+(window._gtm.scroll||\"0\"),\"\");window._gtm.ga.forceTrack()});\u003C\/script\u003E",
      "vtp_supportDocumentWrite":false,
      "vtp_enableIframeMode":false,
      "vtp_enableEditJsMacroBehavior":false,
      "tag_id":2
    }],
  "predicates":[{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"ad.impression"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.js"
    },{
      "function":"_eq",
      "arg0":["macro",1],
      "arg1":"bildergalerien"
    },{
      "function":"_re",
      "arg0":["macro",2],
      "arg1":"^m\\.stage\\.sport1\\.de$|^www\\.stage\\.sport1\\.de$",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",0],
      "arg1":"^view\\.page$"
    },{
      "function":"_re",
      "arg0":["macro",0],
      "arg1":"^view\\.ivw$"
    },{
      "function":"_re",
      "arg0":["macro",3],
      "arg1":".*sport1\\.de.+"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"site.info"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"page.info"
    },{
      "function":"_re",
      "arg0":["macro",0],
      "arg1":"interaction"
    },{
      "function":"_re",
      "arg0":["macro",14],
      "arg1":"tipico|inline-bet"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"view.ivw"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"ivw.info"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"ad.click"
    },{
      "function":"_re",
      "arg0":["macro",3],
      "arg1":"https:\/\/www.sport1.de\/internationaler-fussball\/la-liga\/*"
    },{
      "function":"_eq",
      "arg0":["macro",3],
      "arg1":"https:\/\/www.sport1.de\/internationaler-fussball\/la-liga"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.dom"
    },{
      "function":"_re",
      "arg0":["macro",3],
      "arg1":"https:\/\/www.sport1.de\/us-sport\/nba\/*"
    },{
      "function":"_eq",
      "arg0":["macro",3],
      "arg1":"https:\/\/www.sport1.de\/us-sport\/nba"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"campaign-decided"
    },{
      "function":"_re",
      "arg0":["macro",3],
      "arg1":".*"
    },{
      "function":"_sw",
      "arg0":["macro",2],
      "arg1":"assets.sport1.de"
    },{
      "function":"_cn",
      "arg0":["macro",2],
      "arg1":"tipico.com"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"optimizely-referrer-override"
    },{
      "function":"_re",
      "arg0":["macro",22],
      "arg1":".*sport1\\.de.+"
    },{
      "function":"_re",
      "arg0":["macro",22],
      "arg1":"^$"
    },{
      "function":"_cn",
      "arg0":["macro",22],
      "arg1":"javascript:"
    },{
      "function":"_cn",
      "arg0":["macro",22],
      "arg1":"mailto:"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.linkClick"
    },{
      "function":"_re",
      "arg0":["macro",23],
      "arg1":"(^$|((^|,)9010567_34($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",26],
      "arg1":"video|livestream",
      "ignore_case":true
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"ga_event"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.scrollDepth"
    },{
      "function":"_re",
      "arg0":["macro",23],
      "arg1":"(^$|((^|,)9010567_41($|,)))"
    },{
      "function":"_re",
      "arg0":["macro",0],
      "arg1":"social\\."
    },{
      "function":"_re",
      "arg0":["macro",15],
      "arg1":"video",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",16],
      "arg1":"initialisierung",
      "ignore_case":true
    },{
      "function":"_re",
      "arg0":["macro",1],
      "arg1":"artikel|bildergalerien"
    },{
      "function":"_eq",
      "arg0":["macro",41],
      "arg1":"\/"
    },{
      "function":"_re",
      "arg0":["macro",2],
      "arg1":"(^www.stage.sport1.de$|^m.stage.sport1.de$)"
    },{
      "function":"_re",
      "arg0":["macro",41],
      "arg1":"(^\\\/fussball\\\/champions-league\\\/|^\\\/fussball\\\/europa-league\\\/|^\\\/internationaler-fussball\\\/premier-league\\\/)[0-9][0-9][0-9][0-9]\\\/[0-9][0-9]"
    },{
      "function":"_ew",
      "arg0":["macro",6],
      "arg1":"Bildergalerie"
    },{
      "function":"_re",
      "arg0":["macro",2],
      "arg1":"(^www.sport1.de$|^m.sport1.de$)"
    },{
      "function":"_eq",
      "arg0":["macro",42],
      "arg1":"false"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"view.page"
    },{
      "function":"_eq",
      "arg0":["macro",42],
      "arg1":"true"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"gtm.load"
    },{
      "function":"_eq",
      "arg0":["macro",0],
      "arg1":"atiTagInit"
    },{
      "function":"_eq",
      "arg0":["macro",66],
      "arg1":"true"
    },{
      "function":"_eq",
      "arg0":["macro",68],
      "arg1":"false"
    },{
      "function":"_eq",
      "arg0":["macro",66],
      "arg1":"false"
    }],
  "rules":[
    [["if",0],["add",8,15,43]],
    [["if",1],["add",9,12]],
    [["if",2,3,4],["add",10]],
    [["if",2,3,5],["add",10]],
    [["if",1,6],["add",11]],
    [["if",7],["add",47,14]],
    [["if",4],["add",44]],
    [["if",8],["add",4,13,28,7]],
    [["if",9],["add",45,35]],
    [["if",11],["add",46,42]],
    [["if",12],["add",5]],
    [["if",13],["add",16,30,39]],
    [["if",14,16],["unless",15],["add",17]],
    [["if",15,16],["add",18]],
    [["if",16,17],["unless",18],["add",19]],
    [["if",16,18],["add",20]],
    [["if",19],["add",21]],
    [["if",1,20],["unless",21,22],["add",22]],
    [["if",23],["add",23]],
    [["if",28,29],["unless",24,25,26,27],["add",24]],
    [["if",31],["unless",30],["add",25]],
    [["if",30,31],["add",26]],
    [["if",32,33],["add",27]],
    [["if",34],["add",29,36]],
    [["if",9,35,36],["add",0]],
    [["if",9,35],["add",1]],
    [["if",8,37],["add",6]],
    [["if",1,38],["add",31]],
    [["if",1],["unless",38],["add",32]],
    [["if",1,39,40],["unless",41],["add",33]],
    [["if",1,40,42],["unless",41],["add",33]],
    [["if",43,44],["add",34]],
    [["if",44,45],["add",3]],
    [["if",46],["add",37]],
    [["if",47],["add",38]],
    [["if",0,48],["add",40]],
    [["if",0,45,49,50],["add",41]],
    [["if",9,10],["block",45]]]
}